// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package app

import (
	"APT/api/app"
)

type ControllerBasics struct{}

func NewBasics() app.IAppBasics {
	return &ControllerBasics{}
}

type ControllerHotel struct{}

func NewHotel() app.IAppHotel {
	return &ControllerHotel{}
}

type ControllerMember struct{}

func NewMember() app.IAppMember {
	return &ControllerMember{}
}

type ControllerPay struct{}

func NewPay() app.IAppPay {
	return &ControllerPay{}
}

type ControllerTh struct{}

type ControllerVerify struct{}

func NewVerify() app.IAppVerify {
	return &ControllerVerify{}
}

type ControllerTerminal struct{}

func NewTerminal() app.IAppTerminal {
	return &ControllerTerminal{}
}

type ControllerCabinet struct{}

func NewCabinet() app.IAppCabinet {
	return &ControllerCabinet{}
}

type ControllerEmployee struct{}

func NewEmployee() app.IAppEmployee {
	return &ControllerEmployee{}
}

type ControllerFx struct{}

func NewFx() app.IAppFx {
	return &ControllerFx{}
}

type ControllerTravel struct{}

func NewTravel() app.IAppTravel {
	return &ControllerTravel{}
}
