// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"APT/api/admin"
)

type ControllerBasics struct{}

func NewBasics() admin.IAdminBasics {
	return &ControllerBasics{}
}

type ControllerFood struct{}

func NewFood() admin.IAdminFood {
	return &ControllerFood{}
}

type ControllerPms struct{}

func NewPms() admin.IAdminPms {
	return &ControllerPms{}
}

type ControllerSpa struct{}

func NewSpa() admin.IAdminSpa {
	return &ControllerSpa{}
}

type ControllerCar struct{}

func NewCar() admin.IAdminCar {
	return &ControllerCar{}
}

type ControllerTh struct{}

func NewTh() admin.IAdminTh {
	return &ControllerTh{}
}

type ControllerCabinet struct{}

func NewCabinet() admin.IAdminCabinet {
	return &ControllerCabinet{}
}

type ControllerEmployee struct{}

func NewEmployee() admin.IAdminEmployee {
	return &ControllerEmployee{}
}

type ControllerTravel struct{}

func NewTravel() admin.IAdminTravel {
	return &ControllerTravel{}
}
