// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notify

import (
	"APT/api/notify"
)

type ControllerHook struct{}

func NewHook() notify.INotifyHook {
	return &ControllerHook{}
}

type ControllerKefu struct{}

func NewKefu() notify.INotifyKefu {
	return &ControllerKefu{}
}

type ControllerAladdin struct{}

func NewAladdin() notify.INotifyAladdin {
	return &ControllerAladdin{}
}

type ControllerTest struct{}

func NewTest() notify.INotifyTest {
	return &ControllerTest{}
}

type ControllerCabinet struct{}

func NewCabinet() notify.INotifyCabinet {
	return &ControllerCabinet{}
}

type ControllerToreta struct{}

func NewToreta() notify.INotifyToreta {
	return &ControllerToreta{}
}

type ControllerPaypay struct{}

func NewPaypay() notify.INotifyPaypay {
	return &ControllerPaypay{}
}
