// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package appv2

import (
	"APT/api/appv2"
)

type ControllerHotel struct{}

func NewHotel() appv2.IAppv2Hotel {
	return &ControllerHotel{}
}

type ControllerWsApi struct{}

func NewWsApi() appv2.IAppv2WsApi {
	return &ControllerWsApi{}
}
