// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalAiFilePointsDao is internal type for wrapping internal DAO implements.
type internalAiFilePointsDao = *internal.AiFilePointsDao

// aiFilePointsDao is the data access object for table ai_file_points.
// You can define custom methods on it to extend its functionality as you wish.
type aiFilePointsDao struct {
	internalAiFilePointsDao
}

var (
	// AiFilePoints is globally public accessible object for table ai_file_points operations.
	AiFilePoints = aiFilePointsDao{
		internal.NewAiFilePointsDao(),
	}
)

// Fill with you ideas below.
