// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalAiFileDao is internal type for wrapping internal DAO implements.
type internalAiFileDao = *internal.AiFileDao

// aiFileDao is the data access object for table ai_file.
// You can define custom methods on it to extend its functionality as you wish.
type aiFileDao struct {
	internalAiFileDao
}

var (
	// AiFile is globally public accessible object for table ai_file operations.
	AiFile = aiFileDao{
		internal.NewAiFileDao(),
	}
)

// Fill with you ideas below.
