// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalAigcSessionMessageDao is internal type for wrapping internal DAO implements.
type internalAigcSessionMessageDao = *internal.AigcSessionMessageDao

// aigcSessionMessageDao is the data access object for table aigc_session_message.
// You can define custom methods on it to extend its functionality as you wish.
type aigcSessionMessageDao struct {
	internalAigcSessionMessageDao
}

var (
	// AigcSessionMessage is globally public accessible object for table aigc_session_message operations.
	AigcSessionMessage = aigcSessionMessageDao{
		internal.NewAigcSessionMessageDao(),
	}
)

// Fill with you ideas below.
