// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalAigcSessionCollectDao is internal type for wrapping internal DAO implements.
type internalAigcSessionCollectDao = *internal.AigcSessionCollectDao

// aigcSessionCollectDao is the data access object for table aigc_session_collect.
// You can define custom methods on it to extend its functionality as you wish.
type aigcSessionCollectDao struct {
	internalAigcSessionCollectDao
}

var (
	// AigcSessionCollect is globally public accessible object for table aigc_session_collect operations.
	AigcSessionCollect = aigcSessionCollectDao{
		internal.NewAigcSessionCollectDao(),
	}
)

// Fill with you ideas below.
