// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCabinetOrderDao is internal type for wrapping internal DAO implements.
type internalCabinetOrderDao = *internal.CabinetOrderDao

// cabinetOrderDao is the data access object for table hg_cabinet_order.
// You can define custom methods on it to extend its functionality as you wish.
type cabinetOrderDao struct {
	internalCabinetOrderDao
}

var (
	// CabinetOrder is globally public accessible object for table hg_cabinet_order operations.
	CabinetOrder = cabinetOrderDao{
		internal.NewCabinetOrderDao(),
	}
)

// Fill with you ideas below.
