// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCabinetOrderLogDao is internal type for wrapping internal DAO implements.
type internalCabinetOrderLogDao = *internal.CabinetOrderLogDao

// cabinetOrderLogDao is the data access object for table hg_cabinet_order_log.
// You can define custom methods on it to extend its functionality as you wish.
type cabinetOrderLogDao struct {
	internalCabinetOrderLogDao
}

var (
	// CabinetOrderLog is globally public accessible object for table hg_cabinet_order_log operations.
	CabinetOrderLog = cabinetOrderLogDao{
		internal.NewCabinetOrderLogDao(),
	}
)

// Fill with you ideas below.
