// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarCarTypeDao is internal type for wrapping internal DAO implements.
type internalCarCarTypeDao = *internal.CarCarTypeDao

// carCarTypeDao is the data access object for table hg_car_car_type.
// You can define custom methods on it to extend its functionality as you wish.
type carCarTypeDao struct {
	internalCarCarTypeDao
}

var (
	// CarCarType is globally public accessible object for table hg_car_car_type operations.
	CarCarType = carCarTypeDao{
		internal.NewCarCarTypeDao(),
	}
)

// Fill with you ideas below.
