// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarOrderLogDao is internal type for wrapping internal DAO implements.
type internalCarOrderLogDao = *internal.CarOrderLogDao

// carOrderLogDao is the data access object for table hg_car_order_log.
// You can define custom methods on it to extend its functionality as you wish.
type carOrderLogDao struct {
	internalCarOrderLogDao
}

var (
	// CarOrderLog is globally public accessible object for table hg_car_order_log operations.
	CarOrderLog = carOrderLogDao{
		internal.NewCarOrderLogDao(),
	}
)

// Fill with you ideas below.
