// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarServiceAddressDao is internal type for wrapping internal DAO implements.
type internalCarServiceAddressDao = *internal.CarServiceAddressDao

// carServiceAddressDao is the data access object for table hg_car_service_address.
// You can define custom methods on it to extend its functionality as you wish.
type carServiceAddressDao struct {
	internalCarServiceAddressDao
}

var (
	// CarServiceAddress is globally public accessible object for table hg_car_service_address operations.
	CarServiceAddress = carServiceAddressDao{
		internal.NewCarServiceAddressDao(),
	}
)

// Fill with you ideas below.
