// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarAddressDao is internal type for wrapping internal DAO implements.
type internalCarAddressDao = *internal.CarAddressDao

// carAddressDao is the data access object for table hg_car_address.
// You can define custom methods on it to extend its functionality as you wish.
type carAddressDao struct {
	internalCarAddressDao
}

var (
	// CarAddress is globally public accessible object for table hg_car_address operations.
	CarAddress = carAddressDao{
		internal.NewCarAddressDao(),
	}
)

// Fill with you ideas below.
