// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarServiceDao is internal type for wrapping internal DAO implements.
type internalCarServiceDao = *internal.CarServiceDao

// carServiceDao is the data access object for table hg_car_service.
// You can define custom methods on it to extend its functionality as you wish.
type carServiceDao struct {
	internalCarServiceDao
}

var (
	// CarService is globally public accessible object for table hg_car_service operations.
	CarService = carServiceDao{
		internal.NewCarServiceDao(),
	}
)

// Fill with you ideas below.
