// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarSettlementDao is internal type for wrapping internal DAO implements.
type internalCarSettlementDao = *internal.CarSettlementDao

// carSettlementDao is the data access object for table hg_car_settlement.
// You can define custom methods on it to extend its functionality as you wish.
type carSettlementDao struct {
	internalCarSettlementDao
}

var (
	// CarSettlement is globally public accessible object for table hg_car_settlement operations.
	CarSettlement = carSettlementDao{
		internal.NewCarSettlementDao(),
	}
)

// Fill with you ideas below.
