// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarDriverBalanceChangeDao is internal type for wrapping internal DAO implements.
type internalCarDriverBalanceChangeDao = *internal.CarDriverBalanceChangeDao

// carDriverBalanceChangeDao is the data access object for table hg_car_driver_balance_change.
// You can define custom methods on it to extend its functionality as you wish.
type carDriverBalanceChangeDao struct {
	internalCarDriverBalanceChangeDao
}

var (
	// CarDriverBalanceChange is globally public accessible object for table hg_car_driver_balance_change operations.
	CarDriverBalanceChange = carDriverBalanceChangeDao{
		internal.NewCarDriverBalanceChangeDao(),
	}
)

// Fill with you ideas below.
