// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarMaintenanceDao is internal type for wrapping internal DAO implements.
type internalCarMaintenanceDao = *internal.CarMaintenanceDao

// carMaintenanceDao is the data access object for table hg_car_maintenance.
// You can define custom methods on it to extend its functionality as you wish.
type carMaintenanceDao struct {
	internalCarMaintenanceDao
}

var (
	// CarMaintenance is globally public accessible object for table hg_car_maintenance operations.
	CarMaintenance = carMaintenanceDao{
		internal.NewCarMaintenanceDao(),
	}
)

// Fill with you ideas below.
