// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarCooperateTypeDao is internal type for wrapping internal DAO implements.
type internalCarCooperateTypeDao = *internal.CarCooperateTypeDao

// carCooperateTypeDao is the data access object for table hg_car_cooperate_type.
// You can define custom methods on it to extend its functionality as you wish.
type carCooperateTypeDao struct {
	internalCarCooperateTypeDao
}

var (
	// CarCooperateType is globally public accessible object for table hg_car_cooperate_type operations.
	CarCooperateType = carCooperateTypeDao{
		internal.NewCarCooperateTypeDao(),
	}
)

// Fill with you ideas below.
