// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarCarDao is internal type for wrapping internal DAO implements.
type internalCarCarDao = *internal.CarCarDao

// carCarDao is the data access object for table hg_car_car.
// You can define custom methods on it to extend its functionality as you wish.
type carCarDao struct {
	internalCarCarDao
}

var (
	// CarCar is globally public accessible object for table hg_car_car operations.
	CarCar = carCarDao{
		internal.NewCarCarDao(),
	}
)

// Fill with you ideas below.
