// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarDriverDao is internal type for wrapping internal DAO implements.
type internalCarDriverDao = *internal.CarDriverDao

// carDriverDao is the data access object for table hg_car_driver.
// You can define custom methods on it to extend its functionality as you wish.
type carDriverDao struct {
	internalCarDriverDao
}

var (
	// CarDriver is globally public accessible object for table hg_car_driver operations.
	CarDriver = carDriverDao{
		internal.NewCarDriverDao(),
	}
)

// Fill with you ideas below.
