// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarHelpDao is internal type for wrapping internal DAO implements.
type internalCarHelpDao = *internal.CarHelpDao

// carHelpDao is the data access object for table hg_car_help.
// You can define custom methods on it to extend its functionality as you wish.
type carHelpDao struct {
	internalCarHelpDao
}

var (
	// CarHelp is globally public accessible object for table hg_car_help operations.
	CarHelp = carHelpDao{
		internal.NewCarHelpDao(),
	}
)

// Fill with you ideas below.
