// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarAddressTypeDao is internal type for wrapping internal DAO implements.
type internalCarAddressTypeDao = *internal.CarAddressTypeDao

// carAddressTypeDao is the data access object for table hg_car_address_type.
// You can define custom methods on it to extend its functionality as you wish.
type carAddressTypeDao struct {
	internalCarAddressTypeDao
}

var (
	// CarAddressType is globally public accessible object for table hg_car_address_type operations.
	CarAddressType = carAddressTypeDao{
		internal.NewCarAddressTypeDao(),
	}
)

// Fill with you ideas below.
