// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarDriverWithdrawDao is internal type for wrapping internal DAO implements.
type internalCarDriverWithdrawDao = *internal.CarDriverWithdrawDao

// carDriverWithdrawDao is the data access object for table hg_car_driver_withdraw.
// You can define custom methods on it to extend its functionality as you wish.
type carDriverWithdrawDao struct {
	internalCarDriverWithdrawDao
}

var (
	// CarDriverWithdraw is globally public accessible object for table hg_car_driver_withdraw operations.
	CarDriverWithdraw = carDriverWithdrawDao{
		internal.NewCarDriverWithdrawDao(),
	}
)

// Fill with you ideas below.
