// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarSettlementOrderDao is internal type for wrapping internal DAO implements.
type internalCarSettlementOrderDao = *internal.CarSettlementOrderDao

// carSettlementOrderDao is the data access object for table hg_car_settlement_order.
// You can define custom methods on it to extend its functionality as you wish.
type carSettlementOrderDao struct {
	internalCarSettlementOrderDao
}

var (
	// CarSettlementOrder is globally public accessible object for table hg_car_settlement_order operations.
	CarSettlementOrder = carSettlementOrderDao{
		internal.NewCarSettlementOrderDao(),
	}
)

// Fill with you ideas below.
