// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarDriverReturnOrderDao is internal type for wrapping internal DAO implements.
type internalCarDriverReturnOrderDao = *internal.CarDriverReturnOrderDao

// carDriverReturnOrderDao is the data access object for table hg_car_driver_return_order.
// You can define custom methods on it to extend its functionality as you wish.
type carDriverReturnOrderDao struct {
	internalCarDriverReturnOrderDao
}

var (
	// CarDriverReturnOrder is globally public accessible object for table hg_car_driver_return_order operations.
	CarDriverReturnOrder = carDriverReturnOrderDao{
		internal.NewCarDriverReturnOrderDao(),
	}
)

// Fill with you ideas below.
