// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarBannerDao is internal type for wrapping internal DAO implements.
type internalCarBannerDao = *internal.CarBannerDao

// carBannerDao is the data access object for table hg_car_banner.
// You can define custom methods on it to extend its functionality as you wish.
type carBannerDao struct {
	internalCarBannerDao
}

var (
	// CarBanner is globally public accessible object for table hg_car_banner operations.
	CarBanner = carBannerDao{
		internal.NewCarBannerDao(),
	}
)

// Fill with you ideas below.
