// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCarOrderDao is internal type for wrapping internal DAO implements.
type internalCarOrderDao = *internal.CarOrderDao

// carOrderDao is the data access object for table hg_car_order.
// You can define custom methods on it to extend its functionality as you wish.
type carOrderDao struct {
	internalCarOrderDao
}

var (
	// CarOrder is globally public accessible object for table hg_car_order operations.
	CarOrder = carOrderDao{
		internal.NewCarOrderDao(),
	}
)

// Fill with you ideas below.
