// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCmsCateDao is internal type for wrapping internal DAO implements.
type internalCmsCateDao = *internal.CmsCateDao

// cmsCateDao is the data access object for table cms_cate.
// You can define custom methods on it to extend its functionality as you wish.
type cmsCateDao struct {
	internalCmsCateDao
}

var (
	// CmsCate is globally public accessible object for table cms_cate operations.
	CmsCate = cmsCateDao{
		internal.NewCmsCateDao(),
	}
)

// Fill with you ideas below.
