// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCmsNewsDao is internal type for wrapping internal DAO implements.
type internalCmsNewsDao = *internal.CmsNewsDao

// cmsNewsDao is the data access object for table cms_news.
// You can define custom methods on it to extend its functionality as you wish.
type cmsNewsDao struct {
	internalCmsNewsDao
}

var (
	// CmsNews is globally public accessible object for table cms_news operations.
	CmsNews = cmsNewsDao{
		internal.NewCmsNewsDao(),
	}
)

// Fill with you ideas below.
