// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalConsumerDao is internal type for wrapping internal DAO implements.
type internalConsumerDao = *internal.ConsumerDao

// consumerDao is the data access object for table consumer.
// You can define custom methods on it to extend its functionality as you wish.
type consumerDao struct {
	internalConsumerDao
}

var (
	// Consumer is globally public accessible object for table consumer operations.
	Consumer = consumerDao{
		internal.NewConsumerDao(),
	}
)

// Fill with you ideas below.
