// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCrsOrderDao is internal type for wrapping internal DAO implements.
type internalCrsOrderDao = *internal.CrsOrderDao

// crsOrderDao is the data access object for table hg_crs_order.
// You can define custom methods on it to extend its functionality as you wish.
type crsOrderDao struct {
	internalCrsOrderDao
}

var (
	// CrsOrder is globally public accessible object for table hg_crs_order operations.
	CrsOrder = crsOrderDao{
		internal.NewCrsOrderDao(),
	}
)

// Fill with you ideas below.
