// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalCsFastContentDao is internal type for wrapping internal DAO implements.
type internalCsFastContentDao = *internal.CsFastContentDao

// csFastContentDao is the data access object for table hg_cs_fast_content.
// You can define custom methods on it to extend its functionality as you wish.
type csFastContentDao struct {
	internalCsFastContentDao
}

var (
	// CsFastContent is globally public accessible object for table hg_cs_fast_content operations.
	CsFastContent = csFastContentDao{
		internal.NewCsFastContentDao(),
	}
)

// Fill with you ideas below.
