// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalDouyinWebhookDao is internal type for wrapping internal DAO implements.
type internalDouyinWebhookDao = *internal.DouyinWebhookDao

// douyinWebhookDao is the data access object for table douyin_webhook.
// You can define custom methods on it to extend its functionality as you wish.
type douyinWebhookDao struct {
	internalDouyinWebhookDao
}

var (
	// DouyinWebhook is globally public accessible object for table douyin_webhook operations.
	DouyinWebhook = douyinWebhookDao{
		internal.NewDouyinWebhookDao(),
	}
)

// Fill with you ideas below.
