// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalEmployeeActivityDepartmentDao is internal type for wrapping internal DAO implements.
type internalEmployeeActivityDepartmentDao = *internal.EmployeeActivityDepartmentDao

// employeeActivityDepartmentDao is the data access object for table hg_employee_activity_department.
// You can define custom methods on it to extend its functionality as you wish.
type employeeActivityDepartmentDao struct {
	internalEmployeeActivityDepartmentDao
}

var (
	// EmployeeActivityDepartment is globally public accessible object for table hg_employee_activity_department operations.
	EmployeeActivityDepartment = employeeActivityDepartmentDao{
		internal.NewEmployeeActivityDepartmentDao(),
	}
)

// Fill with you ideas below.
