// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalEmployeeActivityDao is internal type for wrapping internal DAO implements.
type internalEmployeeActivityDao = *internal.EmployeeActivityDao

// employeeActivityDao is the data access object for table hg_employee_activity.
// You can define custom methods on it to extend its functionality as you wish.
type employeeActivityDao struct {
	internalEmployeeActivityDao
}

var (
	// EmployeeActivity is globally public accessible object for table hg_employee_activity operations.
	EmployeeActivity = employeeActivityDao{
		internal.NewEmployeeActivityDao(),
	}
)

// Fill with you ideas below.
