// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalEmployeeDepartmentDao is internal type for wrapping internal DAO implements.
type internalEmployeeDepartmentDao = *internal.EmployeeDepartmentDao

// employeeDepartmentDao is the data access object for table hg_employee_department.
// You can define custom methods on it to extend its functionality as you wish.
type employeeDepartmentDao struct {
	internalEmployeeDepartmentDao
}

var (
	// EmployeeDepartment is globally public accessible object for table hg_employee_department operations.
	EmployeeDepartment = employeeDepartmentDao{
		internal.NewEmployeeDepartmentDao(),
	}
)

// Fill with you ideas below.
