// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalEmployeeActivityCouponDao is internal type for wrapping internal DAO implements.
type internalEmployeeActivityCouponDao = *internal.EmployeeActivityCouponDao

// employeeActivityCouponDao is the data access object for table hg_employee_activity_coupon.
// You can define custom methods on it to extend its functionality as you wish.
type employeeActivityCouponDao struct {
	internalEmployeeActivityCouponDao
}

var (
	// EmployeeActivityCoupon is globally public accessible object for table hg_employee_activity_coupon operations.
	EmployeeActivityCoupon = employeeActivityCouponDao{
		internal.NewEmployeeActivityCouponDao(),
	}
)

// Fill with you ideas below.
