// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalEmployeeActivityEmployeeDao is internal type for wrapping internal DAO implements.
type internalEmployeeActivityEmployeeDao = *internal.EmployeeActivityEmployeeDao

// employeeActivityEmployeeDao is the data access object for table hg_employee_activity_employee.
// You can define custom methods on it to extend its functionality as you wish.
type employeeActivityEmployeeDao struct {
	internalEmployeeActivityEmployeeDao
}

var (
	// EmployeeActivityEmployee is globally public accessible object for table hg_employee_activity_employee operations.
	EmployeeActivityEmployee = employeeActivityEmployeeDao{
		internal.NewEmployeeActivityEmployeeDao(),
	}
)

// Fill with you ideas below.
