// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalEntConfigDao is internal type for wrapping internal DAO implements.
type internalEntConfigDao = *internal.EntConfigDao

// entConfigDao is the data access object for table ent_config.
// You can define custom methods on it to extend its functionality as you wish.
type entConfigDao struct {
	internalEntConfigDao
}

var (
	// EntConfig is globally public accessible object for table ent_config operations.
	EntConfig = entConfigDao{
		internal.NewEntConfigDao(),
	}
)

// Fill with you ideas below.
