// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFlyLogDao is internal type for wrapping internal DAO implements.
type internalFlyLogDao = *internal.FlyLogDao

// flyLogDao is the data access object for table fly_log.
// You can define custom methods on it to extend its functionality as you wish.
type flyLogDao struct {
	internalFlyLogDao
}

var (
	// FlyLog is globally public accessible object for table fly_log operations.
	FlyLog = flyLogDao{
		internal.NewFlyLogDao(),
	}
)

// Fill with you ideas below.
