// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodMaintenanceDao is internal type for wrapping internal DAO implements.
type internalFoodMaintenanceDao = *internal.FoodMaintenanceDao

// foodMaintenanceDao is the data access object for table hg_food_maintenance.
// You can define custom methods on it to extend its functionality as you wish.
type foodMaintenanceDao struct {
	internalFoodMaintenanceDao
}

var (
	// FoodMaintenance is globally public accessible object for table hg_food_maintenance operations.
	FoodMaintenance = foodMaintenanceDao{
		internal.NewFoodMaintenanceDao(),
	}
)

// Fill with you ideas below.
