// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodSettlementAccountDao is internal type for wrapping internal DAO implements.
type internalFoodSettlementAccountDao = *internal.FoodSettlementAccountDao

// foodSettlementAccountDao is the data access object for table hg_food_settlement_account.
// You can define custom methods on it to extend its functionality as you wish.
type foodSettlementAccountDao struct {
	internalFoodSettlementAccountDao
}

var (
	// FoodSettlementAccount is globally public accessible object for table hg_food_settlement_account operations.
	FoodSettlementAccount = foodSettlementAccountDao{
		internal.NewFoodSettlementAccountDao(),
	}
)

// Fill with you ideas below.
