// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodRestaurantMemberDao is internal type for wrapping internal DAO implements.
type internalFoodRestaurantMemberDao = *internal.FoodRestaurantMemberDao

// foodRestaurantMemberDao is the data access object for table hg_food_restaurant_member.
// You can define custom methods on it to extend its functionality as you wish.
type foodRestaurantMemberDao struct {
	internalFoodRestaurantMemberDao
}

var (
	// FoodRestaurantMember is globally public accessible object for table hg_food_restaurant_member operations.
	FoodRestaurantMember = foodRestaurantMemberDao{
		internal.NewFoodRestaurantMemberDao(),
	}
)

// Fill with you ideas below.
