// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodOrderLogDao is internal type for wrapping internal DAO implements.
type internalFoodOrderLogDao = *internal.FoodOrderLogDao

// foodOrderLogDao is the data access object for table hg_food_order_log.
// You can define custom methods on it to extend its functionality as you wish.
type foodOrderLogDao struct {
	internalFoodOrderLogDao
}

var (
	// FoodOrderLog is globally public accessible object for table hg_food_order_log operations.
	FoodOrderLog = foodOrderLogDao{
		internal.NewFoodOrderLogDao(),
	}
)

// Fill with you ideas below.
