// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodCuisineDao is internal type for wrapping internal DAO implements.
type internalFoodCuisineDao = *internal.FoodCuisineDao

// foodCuisineDao is the data access object for table hg_food_cuisine.
// You can define custom methods on it to extend its functionality as you wish.
type foodCuisineDao struct {
	internalFoodCuisineDao
}

var (
	// FoodCuisine is globally public accessible object for table hg_food_cuisine operations.
	FoodCuisine = foodCuisineDao{
		internal.NewFoodCuisineDao(),
	}
)

// Fill with you ideas below.
