// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodSettlementDao is internal type for wrapping internal DAO implements.
type internalFoodSettlementDao = *internal.FoodSettlementDao

// foodSettlementDao is the data access object for table hg_food_settlement.
// You can define custom methods on it to extend its functionality as you wish.
type foodSettlementDao struct {
	internalFoodSettlementDao
}

var (
	// FoodSettlement is globally public accessible object for table hg_food_settlement operations.
	FoodSettlement = foodSettlementDao{
		internal.NewFoodSettlementDao(),
	}
)

// Fill with you ideas below.
