// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodCooperateTypeDao is internal type for wrapping internal DAO implements.
type internalFoodCooperateTypeDao = *internal.FoodCooperateTypeDao

// foodCooperateTypeDao is the data access object for table hg_food_cooperate_type.
// You can define custom methods on it to extend its functionality as you wish.
type foodCooperateTypeDao struct {
	internalFoodCooperateTypeDao
}

var (
	// FoodCooperateType is globally public accessible object for table hg_food_cooperate_type operations.
	FoodCooperateType = foodCooperateTypeDao{
		internal.NewFoodCooperateTypeDao(),
	}
)

// Fill with you ideas below.
