// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodAreaDao is internal type for wrapping internal DAO implements.
type internalFoodAreaDao = *internal.FoodAreaDao

// foodAreaDao is the data access object for table hg_food_area.
// You can define custom methods on it to extend its functionality as you wish.
type foodAreaDao struct {
	internalFoodAreaDao
}

var (
	// FoodArea is globally public accessible object for table hg_food_area operations.
	FoodArea = foodAreaDao{
		internal.NewFoodAreaDao(),
	}
)

// Fill with you ideas below.
