// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodRestaurantCuisineDao is internal type for wrapping internal DAO implements.
type internalFoodRestaurantCuisineDao = *internal.FoodRestaurantCuisineDao

// foodRestaurantCuisineDao is the data access object for table hg_food_restaurant_cuisine.
// You can define custom methods on it to extend its functionality as you wish.
type foodRestaurantCuisineDao struct {
	internalFoodRestaurantCuisineDao
}

var (
	// FoodRestaurantCuisine is globally public accessible object for table hg_food_restaurant_cuisine operations.
	FoodRestaurantCuisine = foodRestaurantCuisineDao{
		internal.NewFoodRestaurantCuisineDao(),
	}
)

// Fill with you ideas below.
