// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodActivityDao is internal type for wrapping internal DAO implements.
type internalFoodActivityDao = *internal.FoodActivityDao

// foodActivityDao is the data access object for table hg_food_activity.
// You can define custom methods on it to extend its functionality as you wish.
type foodActivityDao struct {
	internalFoodActivityDao
}

var (
	// FoodActivity is globally public accessible object for table hg_food_activity operations.
	FoodActivity = foodActivityDao{
		internal.NewFoodActivityDao(),
	}
)

// Fill with you ideas below.
