// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodOrderDao is internal type for wrapping internal DAO implements.
type internalFoodOrderDao = *internal.FoodOrderDao

// foodOrderDao is the data access object for table hg_food_order.
// You can define custom methods on it to extend its functionality as you wish.
type foodOrderDao struct {
	internalFoodOrderDao
}

var (
	// FoodOrder is globally public accessible object for table hg_food_order operations.
	FoodOrder = foodOrderDao{
		internal.NewFoodOrderDao(),
	}
)

// Fill with you ideas below.
