// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodRestaurantNoticeDao is internal type for wrapping internal DAO implements.
type internalFoodRestaurantNoticeDao = *internal.FoodRestaurantNoticeDao

// foodRestaurantNoticeDao is the data access object for table hg_food_restaurant_notice.
// You can define custom methods on it to extend its functionality as you wish.
type foodRestaurantNoticeDao struct {
	internalFoodRestaurantNoticeDao
}

var (
	// FoodRestaurantNotice is globally public accessible object for table hg_food_restaurant_notice operations.
	FoodRestaurantNotice = foodRestaurantNoticeDao{
		internal.NewFoodRestaurantNoticeDao(),
	}
)

// Fill with you ideas below.
