// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodSeatDao is internal type for wrapping internal DAO implements.
type internalFoodSeatDao = *internal.FoodSeatDao

// foodSeatDao is the data access object for table hg_food_seat.
// You can define custom methods on it to extend its functionality as you wish.
type foodSeatDao struct {
	internalFoodSeatDao
}

var (
	// FoodSeat is globally public accessible object for table hg_food_seat operations.
	FoodSeat = foodSeatDao{
		internal.NewFoodSeatDao(),
	}
)

// Fill with you ideas below.
