// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodSettlementOrderDao is internal type for wrapping internal DAO implements.
type internalFoodSettlementOrderDao = *internal.FoodSettlementOrderDao

// foodSettlementOrderDao is the data access object for table hg_food_settlement_order.
// You can define custom methods on it to extend its functionality as you wish.
type foodSettlementOrderDao struct {
	internalFoodSettlementOrderDao
}

var (
	// FoodSettlementOrder is globally public accessible object for table hg_food_settlement_order operations.
	FoodSettlementOrder = foodSettlementOrderDao{
		internal.NewFoodSettlementOrderDao(),
	}
)

// Fill with you ideas below.
