// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodRestaurantDao is internal type for wrapping internal DAO implements.
type internalFoodRestaurantDao = *internal.FoodRestaurantDao

// foodRestaurantDao is the data access object for table hg_food_restaurant.
// You can define custom methods on it to extend its functionality as you wish.
type foodRestaurantDao struct {
	internalFoodRestaurantDao
}

var (
	// FoodRestaurant is globally public accessible object for table hg_food_restaurant operations.
	FoodRestaurant = foodRestaurantDao{
		internal.NewFoodRestaurantDao(),
	}
)

// Fill with you ideas below.
