// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodRestaurantOperateLogDao is internal type for wrapping internal DAO implements.
type internalFoodRestaurantOperateLogDao = *internal.FoodRestaurantOperateLogDao

// foodRestaurantOperateLogDao is the data access object for table hg_food_restaurant_operate_log.
// You can define custom methods on it to extend its functionality as you wish.
type foodRestaurantOperateLogDao struct {
	internalFoodRestaurantOperateLogDao
}

var (
	// FoodRestaurantOperateLog is globally public accessible object for table hg_food_restaurant_operate_log operations.
	FoodRestaurantOperateLog = foodRestaurantOperateLogDao{
		internal.NewFoodRestaurantOperateLogDao(),
	}
)

// Fill with you ideas below.
