// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodActivityRestaurantDao is internal type for wrapping internal DAO implements.
type internalFoodActivityRestaurantDao = *internal.FoodActivityRestaurantDao

// foodActivityRestaurantDao is the data access object for table hg_food_activity_restaurant.
// You can define custom methods on it to extend its functionality as you wish.
type foodActivityRestaurantDao struct {
	internalFoodActivityRestaurantDao
}

var (
	// FoodActivityRestaurant is globally public accessible object for table hg_food_activity_restaurant operations.
	FoodActivityRestaurant = foodActivityRestaurantDao{
		internal.NewFoodActivityRestaurantDao(),
	}
)

// Fill with you ideas below.
