// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodLabelDao is internal type for wrapping internal DAO implements.
type internalFoodLabelDao = *internal.FoodLabelDao

// foodLabelDao is the data access object for table hg_food_label.
// You can define custom methods on it to extend its functionality as you wish.
type foodLabelDao struct {
	internalFoodLabelDao
}

var (
	// FoodLabel is globally public accessible object for table hg_food_label operations.
	FoodLabel = foodLabelDao{
		internal.NewFoodLabelDao(),
	}
)

// Fill with you ideas below.
