// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodRestaurantSeatDao is internal type for wrapping internal DAO implements.
type internalFoodRestaurantSeatDao = *internal.FoodRestaurantSeatDao

// foodRestaurantSeatDao is the data access object for table hg_food_restaurant_seat.
// You can define custom methods on it to extend its functionality as you wish.
type foodRestaurantSeatDao struct {
	internalFoodRestaurantSeatDao
}

var (
	// FoodRestaurantSeat is globally public accessible object for table hg_food_restaurant_seat operations.
	FoodRestaurantSeat = foodRestaurantSeatDao{
		internal.NewFoodRestaurantSeatDao(),
	}
)

// Fill with you ideas below.
