// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalFoodRestaurantTerminalDao is internal type for wrapping internal DAO implements.
type internalFoodRestaurantTerminalDao = *internal.FoodRestaurantTerminalDao

// foodRestaurantTerminalDao is the data access object for table hg_food_restaurant_terminal.
// You can define custom methods on it to extend its functionality as you wish.
type foodRestaurantTerminalDao struct {
	internalFoodRestaurantTerminalDao
}

var (
	// FoodRestaurantTerminal is globally public accessible object for table hg_food_restaurant_terminal operations.
	FoodRestaurantTerminal = foodRestaurantTerminalDao{
		internal.NewFoodRestaurantTerminalDao(),
	}
)

// Fill with you ideas below.
