// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalHomepageArticleLinksDao is an internal type for wrapping the internal DAO implementation.
type internalHomepageArticleLinksDao = *internal.HomepageArticleLinksDao

// homepageArticleLinksDao is the data access object for the table hg_homepage_article_links.
// You can define custom methods on it to extend its functionality as needed.
type homepageArticleLinksDao struct {
	internalHomepageArticleLinksDao
}

var (
	// HomepageArticleLinks is a globally accessible object for table hg_homepage_article_links operations.
	HomepageArticleLinks = homepageArticleLinksDao{
		internal.NewHomepageArticleLinksDao(),
	}
)

// Add your custom methods and functionality below.
