// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalHomepageArticleThumbDao is an internal type for wrapping the internal DAO implementation.
type internalHomepageArticleThumbDao = *internal.HomepageArticleThumbDao

// homepageArticleThumbDao is the data access object for the table hg_homepage_article_thumb.
// You can define custom methods on it to extend its functionality as needed.
type homepageArticleThumbDao struct {
	internalHomepageArticleThumbDao
}

var (
	// HomepageArticleThumb is a globally accessible object for table hg_homepage_article_thumb operations.
	HomepageArticleThumb = homepageArticleThumbDao{
		internal.NewHomepageArticleThumbDao(),
	}
)

// Add your custom methods and functionality below.
