// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalHomepageArticleCouponDao is an internal type for wrapping the internal DAO implementation.
type internalHomepageArticleCouponDao = *internal.HomepageArticleCouponDao

// homepageArticleCouponDao is the data access object for the table hg_homepage_article_coupon.
// You can define custom methods on it to extend its functionality as needed.
type homepageArticleCouponDao struct {
	internalHomepageArticleCouponDao
}

var (
	// HomepageArticleCoupon is a globally accessible object for table hg_homepage_article_coupon operations.
	HomepageArticleCoupon = homepageArticleCouponDao{
		internal.NewHomepageArticleCouponDao(),
	}
)

// Add your custom methods and functionality below.
