// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalHomepageArticlesDao is an internal type for wrapping the internal DAO implementation.
type internalHomepageArticlesDao = *internal.HomepageArticlesDao

// homepageArticlesDao is the data access object for the table hg_homepage_articles.
// You can define custom methods on it to extend its functionality as needed.
type homepageArticlesDao struct {
	internalHomepageArticlesDao
}

var (
	// HomepageArticles is a globally accessible object for table hg_homepage_articles operations.
	HomepageArticles = homepageArticlesDao{
		internal.NewHomepageArticlesDao(),
	}
)

// Add your custom methods and functionality below.
