// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalImMessageDao is an internal type for wrapping the internal DAO implementation.
type internalImMessageDao = *internal.ImMessageDao

// imMessageDao is the data access object for the table hg_im_message.
// You can define custom methods on it to extend its functionality as needed.
type imMessageDao struct {
	internalImMessageDao
}

var (
	// ImMessage is a globally accessible object for table hg_im_message operations.
	ImMessage = imMessageDao{
		internal.NewImMessageDao(),
	}
)

// Add your custom methods and functionality below.
