// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalImMessageReadDao is an internal type for wrapping the internal DAO implementation.
type internalImMessageReadDao = *internal.ImMessageReadDao

// imMessageReadDao is the data access object for the table hg_im_message_read.
// You can define custom methods on it to extend its functionality as needed.
type imMessageReadDao struct {
	internalImMessageReadDao
}

var (
	// ImMessageRead is a globally accessible object for table hg_im_message_read operations.
	ImMessageRead = imMessageReadDao{
		internal.NewImMessageReadDao(),
	}
)

// Add your custom methods and functionality below.
