// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalIndexBannerDao is internal type for wrapping internal DAO implements.
type internalIndexBannerDao = *internal.IndexBannerDao

// indexBannerDao is the data access object for table hg_index_banner.
// You can define custom methods on it to extend its functionality as you wish.
type indexBannerDao struct {
	internalIndexBannerDao
}

var (
	// IndexBanner is globally public accessible object for table hg_index_banner operations.
	IndexBanner = indexBannerDao{
		internal.NewIndexBannerDao(),
	}
)

// Fill with you ideas below.
