// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalIpAuthDao is internal type for wrapping internal DAO implements.
type internalIpAuthDao = *internal.IpAuthDao

// ipAuthDao is the data access object for table ip_auth.
// You can define custom methods on it to extend its functionality as you wish.
type ipAuthDao struct {
	internalIpAuthDao
}

var (
	// IpAuth is globally public accessible object for table ip_auth operations.
	IpAuth = ipAuthDao{
		internal.NewIpAuthDao(),
	}
)

// Fill with you ideas below.
