// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalIpblackDao is internal type for wrapping internal DAO implements.
type internalIpblackDao = *internal.IpblackDao

// ipblackDao is the data access object for table ipblack.
// You can define custom methods on it to extend its functionality as you wish.
type ipblackDao struct {
	internalIpblackDao
}

var (
	// Ipblack is globally public accessible object for table ipblack operations.
	Ipblack = ipblackDao{
		internal.NewIpblackDao(),
	}
)

// Fill with you ideas below.
