// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalLearnDao is internal type for wrapping internal DAO implements.
type internalLearnDao = *internal.LearnDao

// learnDao is the data access object for table learn.
// You can define custom methods on it to extend its functionality as you wish.
type learnDao struct {
	internalLearnDao
}

var (
	// Learn is globally public accessible object for table learn operations.
	Learn = learnDao{
		internal.NewLearnDao(),
	}
)

// Fill with you ideas below.
