// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalNewDao is internal type for wrapping internal DAO implements.
type internalNewDao = *internal.NewDao

// newDao is the data access object for table new.
// You can define custom methods on it to extend its functionality as you wish.
type newDao struct {
	internalNewDao
}

var (
	// New is globally public accessible object for table new operations.
	New = newDao{
		internal.NewNewDao(),
	}
)

// Fill with you ideas below.
