// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalOauthDao is internal type for wrapping internal DAO implements.
type internalOauthDao = *internal.OauthDao

// oauthDao is the data access object for table oauth.
// You can define custom methods on it to extend its functionality as you wish.
type oauthDao struct {
	internalOauthDao
}

var (
	// Oauth is globally public accessible object for table oauth operations.
	Oauth = oauthDao{
		internal.NewOauthDao(),
	}
)

// Fill with you ideas below.
