// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalOrderExportDao is internal type for wrapping internal DAO implements.
type internalOrderExportDao = *internal.OrderExportDao

// orderExportDao is the data access object for table hg_order_export.
// You can define custom methods on it to extend its functionality as you wish.
type orderExportDao struct {
	internalOrderExportDao
}

var (
	// OrderExport is globally public accessible object for table hg_order_export operations.
	OrderExport = orderExportDao{
		internal.NewOrderExportDao(),
	}
)

// Fill with you ideas below.
