// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalOrderRefundLogDao is an internal type for wrapping the internal DAO implementation.
type internalOrderRefundLogDao = *internal.OrderRefundLogDao

// orderRefundLogDao is the data access object for the table hg_order_refund_log.
// You can define custom methods on it to extend its functionality as needed.
type orderRefundLogDao struct {
	internalOrderRefundLogDao
}

var (
	// OrderRefundLog is a globally accessible object for table hg_order_refund_log operations.
	OrderRefundLog = orderRefundLogDao{
		internal.NewOrderRefundLogDao(),
	}
)

// Add your custom methods and functionality below.
