// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsPricePlanDao is internal type for wrapping internal DAO implements.
type internalPmsPricePlanDao = *internal.PmsPricePlanDao

// pmsPricePlanDao is the data access object for table hg_pms_price_plan.
// You can define custom methods on it to extend its functionality as you wish.
type pmsPricePlanDao struct {
	internalPmsPricePlanDao
}

var (
	// PmsPricePlan is globally public accessible object for table hg_pms_price_plan operations.
	PmsPricePlan = pmsPricePlanDao{
		internal.NewPmsPricePlanDao(),
	}
)

// Fill with you ideas below.
