// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsIndexNavDao is internal type for wrapping internal DAO implements.
type internalPmsIndexNavDao = *internal.PmsIndexNavDao

// pmsIndexNavDao is the data access object for table hg_pms_index_nav.
// You can define custom methods on it to extend its functionality as you wish.
type pmsIndexNavDao struct {
	internalPmsIndexNavDao
}

var (
	// PmsIndexNav is globally public accessible object for table hg_pms_index_nav operations.
	PmsIndexNav = pmsIndexNavDao{
		internal.NewPmsIndexNavDao(),
	}
)

// Fill with you ideas below.
