// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsBrokerageDao is internal type for wrapping internal DAO implements.
type internalPmsBrokerageDao = *internal.PmsBrokerageDao

// pmsBrokerageDao is the data access object for table hg_pms_brokerage.
// You can define custom methods on it to extend its functionality as you wish.
type pmsBrokerageDao struct {
	internalPmsBrokerageDao
}

var (
	// PmsBrokerage is globally public accessible object for table hg_pms_brokerage operations.
	PmsBrokerage = pmsBrokerageDao{
		internal.NewPmsBrokerageDao(),
	}
)

// Fill with you ideas below.
