// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsBedTypeDao is internal type for wrapping internal DAO implements.
type internalPmsBedTypeDao = *internal.PmsBedTypeDao

// pmsBedTypeDao is the data access object for table hg_pms_bed_type.
// You can define custom methods on it to extend its functionality as you wish.
type pmsBedTypeDao struct {
	internalPmsBedTypeDao
}

var (
	// PmsBedType is globally public accessible object for table hg_pms_bed_type operations.
	PmsBedType = pmsBedTypeDao{
		internal.NewPmsBedTypeDao(),
	}
)

// Fill with you ideas below.
