// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAppReservationChangeDao is internal type for wrapping internal DAO implements.
type internalPmsAppReservationChangeDao = *internal.PmsAppReservationChangeDao

// pmsAppReservationChangeDao is the data access object for table hg_pms_app_reservation_change.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAppReservationChangeDao struct {
	internalPmsAppReservationChangeDao
}

var (
	// PmsAppReservationChange is globally public accessible object for table hg_pms_app_reservation_change operations.
	PmsAppReservationChange = pmsAppReservationChangeDao{
		internal.NewPmsAppReservationChangeDao(),
	}
)

// Fill with you ideas below.
