// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsCollectDao is internal type for wrapping internal DAO implements.
type internalPmsCollectDao = *internal.PmsCollectDao

// pmsCollectDao is the data access object for table hg_pms_collect.
// You can define custom methods on it to extend its functionality as you wish.
type pmsCollectDao struct {
	internalPmsCollectDao
}

var (
	// PmsCollect is globally public accessible object for table hg_pms_collect operations.
	PmsCollect = pmsCollectDao{
		internal.NewPmsCollectDao(),
	}
)

// Fill with you ideas below.
