// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsBalanceChangeDao is internal type for wrapping internal DAO implements.
type internalPmsBalanceChangeDao = *internal.PmsBalanceChangeDao

// pmsBalanceChangeDao is the data access object for table hg_pms_balance_change.
// You can define custom methods on it to extend its functionality as you wish.
type pmsBalanceChangeDao struct {
	internalPmsBalanceChangeDao
}

var (
	// PmsBalanceChange is globally public accessible object for table hg_pms_balance_change operations.
	PmsBalanceChange = pmsBalanceChangeDao{
		internal.NewPmsBalanceChangeDao(),
	}
)

// Fill with you ideas below.
