// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberLevelDao is internal type for wrapping internal DAO implements.
type internalPmsMemberLevelDao = *internal.PmsMemberLevelDao

// pmsMemberLevelDao is the data access object for table hg_pms_member_level.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberLevelDao struct {
	internalPmsMemberLevelDao
}

var (
	// PmsMemberLevel is globally public accessible object for table hg_pms_member_level operations.
	PmsMemberLevel = pmsMemberLevelDao{
		internal.NewPmsMemberLevelDao(),
	}
)

// Fill with you ideas below.
