// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberAuthDao is internal type for wrapping internal DAO implements.
type internalPmsMemberAuthDao = *internal.PmsMemberAuthDao

// pmsMemberAuthDao is the data access object for table hg_pms_member_auth.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberAuthDao struct {
	internalPmsMemberAuthDao
}

var (
	// PmsMemberAuth is globally public accessible object for table hg_pms_member_auth operations.
	PmsMemberAuth = pmsMemberAuthDao{
		internal.NewPmsMemberAuthDao(),
	}
)

// Fill with you ideas below.
