// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsTestNavDao is internal type for wrapping internal DAO implements.
type internalPmsTestNavDao = *internal.PmsTestNavDao

// pmsTestNavDao is the data access object for table hg_pms_test_nav.
// You can define custom methods on it to extend its functionality as you wish.
type pmsTestNavDao struct {
	internalPmsTestNavDao
}

var (
	// PmsTestNav is globally public accessible object for table hg_pms_test_nav operations.
	PmsTestNav = pmsTestNavDao{
		internal.NewPmsTestNavDao(),
	}
)

// Fill with you ideas below.
