// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsCancelRateDao is internal type for wrapping internal DAO implements.
type internalPmsCancelRateDao = *internal.PmsCancelRateDao

// pmsCancelRateDao is the data access object for table hg_pms_cancel_rate.
// You can define custom methods on it to extend its functionality as you wish.
type pmsCancelRateDao struct {
	internalPmsCancelRateDao
}

var (
	// PmsCancelRate is globally public accessible object for table hg_pms_cancel_rate operations.
	PmsCancelRate = pmsCancelRateDao{
		internal.NewPmsCancelRateDao(),
	}
)

// Fill with you ideas below.
