// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsHelpcenterDao is internal type for wrapping internal DAO implements.
type internalPmsHelpcenterDao = *internal.PmsHelpcenterDao

// pmsHelpcenterDao is the data access object for table hg_pms_helpcenter.
// You can define custom methods on it to extend its functionality as you wish.
type pmsHelpcenterDao struct {
	internalPmsHelpcenterDao
}

var (
	// PmsHelpcenter is globally public accessible object for table hg_pms_helpcenter operations.
	PmsHelpcenter = pmsHelpcenterDao{
		internal.NewPmsHelpcenterDao(),
	}
)

// Fill with you ideas below.
