// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberGroupDao is internal type for wrapping internal DAO implements.
type internalPmsMemberGroupDao = *internal.PmsMemberGroupDao

// pmsMemberGroupDao is the data access object for table hg_pms_member_group.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberGroupDao struct {
	internalPmsMemberGroupDao
}

var (
	// PmsMemberGroup is globally public accessible object for table hg_pms_member_group operations.
	PmsMemberGroup = pmsMemberGroupDao{
		internal.NewPmsMemberGroupDao(),
	}
)

// Fill with you ideas below.
