// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAppStayDao is internal type for wrapping internal DAO implements.
type internalPmsAppStayDao = *internal.PmsAppStayDao

// pmsAppStayDao is the data access object for table hg_pms_app_stay.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAppStayDao struct {
	internalPmsAppStayDao
}

var (
	// PmsAppStay is globally public accessible object for table hg_pms_app_stay operations.
	PmsAppStay = pmsAppStayDao{
		internal.NewPmsAppStayDao(),
	}
)

// Fill with you ideas below.
