// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAppReservationDao is internal type for wrapping internal DAO implements.
type internalPmsAppReservationDao = *internal.PmsAppReservationDao

// pmsAppReservationDao is the data access object for table hg_pms_app_reservation.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAppReservationDao struct {
	internalPmsAppReservationDao
}

var (
	// PmsAppReservation is globally public accessible object for table hg_pms_app_reservation operations.
	PmsAppReservation = pmsAppReservationDao{
		internal.NewPmsAppReservationDao(),
	}
)

// Fill with you ideas below.
