// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAirhostMessageDao is internal type for wrapping internal DAO implements.
type internalPmsAirhostMessageDao = *internal.PmsAirhostMessageDao

// pmsAirhostMessageDao is the data access object for table hg_pms_airhost_message.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAirhostMessageDao struct {
	internalPmsAirhostMessageDao
}

var (
	// PmsAirhostMessage is globally public accessible object for table hg_pms_airhost_message operations.
	PmsAirhostMessage = pmsAirhostMessageDao{
		internal.NewPmsAirhostMessageDao(),
	}
)

// Fill with you ideas below.
