// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAppStayLogDao is internal type for wrapping internal DAO implements.
type internalPmsAppStayLogDao = *internal.PmsAppStayLogDao

// pmsAppStayLogDao is the data access object for table hg_pms_app_stay_log.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAppStayLogDao struct {
	internalPmsAppStayLogDao
}

var (
	// PmsAppStayLog is globally public accessible object for table hg_pms_app_stay_log operations.
	PmsAppStayLog = pmsAppStayLogDao{
		internal.NewPmsAppStayLogDao(),
	}
)

// Fill with you ideas below.
