// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberSceneDao is internal type for wrapping internal DAO implements.
type internalPmsMemberSceneDao = *internal.PmsMemberSceneDao

// pmsMemberSceneDao is the data access object for table hg_pms_member_scene.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberSceneDao struct {
	internalPmsMemberSceneDao
}

var (
	// PmsMemberScene is globally public accessible object for table hg_pms_member_scene operations.
	PmsMemberScene = pmsMemberSceneDao{
		internal.NewPmsMemberSceneDao(),
	}
)

// Fill with you ideas below.
