// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsRoomTypeDao is internal type for wrapping internal DAO implements.
type internalPmsRoomTypeDao = *internal.PmsRoomTypeDao

// pmsRoomTypeDao is the data access object for table hg_pms_room_type.
// You can define custom methods on it to extend its functionality as you wish.
type pmsRoomTypeDao struct {
	internalPmsRoomTypeDao
}

var (
	// PmsRoomType is globally public accessible object for table hg_pms_room_type operations.
	PmsRoomType = pmsRoomTypeDao{
		internal.NewPmsRoomTypeDao(),
	}
)

// Fill with you ideas below.
