// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberDao is internal type for wrapping internal DAO implements.
type internalPmsMemberDao = *internal.PmsMemberDao

// pmsMemberDao is the data access object for table hg_pms_member.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberDao struct {
	internalPmsMemberDao
}

var (
	// PmsMember is globally public accessible object for table hg_pms_member operations.
	PmsMember = pmsMemberDao{
		internal.NewPmsMemberDao(),
	}
)

// Fill with you ideas below.
