// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsRoomGuestDao is internal type for wrapping internal DAO implements.
type internalPmsRoomGuestDao = *internal.PmsRoomGuestDao

// pmsRoomGuestDao is the data access object for table hg_pms_room_guest.
// You can define custom methods on it to extend its functionality as you wish.
type pmsRoomGuestDao struct {
	internalPmsRoomGuestDao
}

var (
	// PmsRoomGuest is globally public accessible object for table hg_pms_room_guest operations.
	PmsRoomGuest = pmsRoomGuestDao{
		internal.NewPmsRoomGuestDao(),
	}
)

// Fill with you ideas below.
