// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsChargeDao is internal type for wrapping internal DAO implements.
type internalPmsChargeDao = *internal.PmsChargeDao

// pmsChargeDao is the data access object for table hg_pms_charge.
// You can define custom methods on it to extend its functionality as you wish.
type pmsChargeDao struct {
	internalPmsChargeDao
}

var (
	// PmsCharge is globally public accessible object for table hg_pms_charge operations.
	PmsCharge = pmsChargeDao{
		internal.NewPmsChargeDao(),
	}
)

// Fill with you ideas below.
