// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAppCancelOrderDao is internal type for wrapping internal DAO implements.
type internalPmsAppCancelOrderDao = *internal.PmsAppCancelOrderDao

// pmsAppCancelOrderDao is the data access object for table hg_pms_app_cancel_order.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAppCancelOrderDao struct {
	internalPmsAppCancelOrderDao
}

var (
	// PmsAppCancelOrder is globally public accessible object for table hg_pms_app_cancel_order operations.
	PmsAppCancelOrder = pmsAppCancelOrderDao{
		internal.NewPmsAppCancelOrderDao(),
	}
)

// Fill with you ideas below.
