// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsTransactionDao is internal type for wrapping internal DAO implements.
type internalPmsTransactionDao = *internal.PmsTransactionDao

// pmsTransactionDao is the data access object for table hg_pms_transaction.
// You can define custom methods on it to extend its functionality as you wish.
type pmsTransactionDao struct {
	internalPmsTransactionDao
}

var (
	// PmsTransaction is globally public accessible object for table hg_pms_transaction operations.
	PmsTransaction = pmsTransactionDao{
		internal.NewPmsTransactionDao(),
	}
)

// Fill with you ideas below.
