// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberCopy1Dao is an internal type for wrapping the internal DAO implementation.
type internalPmsMemberCopy1Dao = *internal.PmsMemberCopy1Dao

// pmsMemberCopy1Dao is the data access object for the table hg_pms_member_copy1.
// You can define custom methods on it to extend its functionality as needed.
type pmsMemberCopy1Dao struct {
	internalPmsMemberCopy1Dao
}

var (
	// PmsMemberCopy1 is a globally accessible object for table hg_pms_member_copy1 operations.
	PmsMemberCopy1 = pmsMemberCopy1Dao{
		internal.NewPmsMemberCopy1Dao(),
	}
)

// Add your custom methods and functionality below.
