// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsFolioDao is internal type for wrapping internal DAO implements.
type internalPmsFolioDao = *internal.PmsFolioDao

// pmsFolioDao is the data access object for table hg_pms_folio.
// You can define custom methods on it to extend its functionality as you wish.
type pmsFolioDao struct {
	internalPmsFolioDao
}

var (
	// PmsFolio is globally public accessible object for table hg_pms_folio operations.
	PmsFolio = pmsFolioDao{
		internal.NewPmsFolioDao(),
	}
)

// Fill with you ideas below.
