// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsNotifyDao is internal type for wrapping internal DAO implements.
type internalPmsNotifyDao = *internal.PmsNotifyDao

// pmsNotifyDao is the data access object for table hg_pms_notify.
// You can define custom methods on it to extend its functionality as you wish.
type pmsNotifyDao struct {
	internalPmsNotifyDao
}

var (
	// PmsNotify is globally public accessible object for table hg_pms_notify operations.
	PmsNotify = pmsNotifyDao{
		internal.NewPmsNotifyDao(),
	}
)

// Fill with you ideas below.
