// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsRoomRatePlanDao is an internal type for wrapping the internal DAO implementation.
type internalPmsRoomRatePlanDao = *internal.PmsRoomRatePlanDao

// pmsRoomRatePlanDao is the data access object for the table hg_pms_room_rate_plan.
// You can define custom methods on it to extend its functionality as needed.
type pmsRoomRatePlanDao struct {
	internalPmsRoomRatePlanDao
}

var (
	// PmsRoomRatePlan is a globally accessible object for table hg_pms_room_rate_plan operations.
	PmsRoomRatePlan = pmsRoomRatePlanDao{
		internal.NewPmsRoomRatePlanDao(),
	}
)

// Add your custom methods and functionality below.
