// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsBannerDao is internal type for wrapping internal DAO implements.
type internalPmsBannerDao = *internal.PmsBannerDao

// pmsBannerDao is the data access object for table hg_pms_banner.
// You can define custom methods on it to extend its functionality as you wish.
type pmsBannerDao struct {
	internalPmsBannerDao
}

var (
	// PmsBanner is globally public accessible object for table hg_pms_banner operations.
	PmsBanner = pmsBannerDao{
		internal.NewPmsBannerDao(),
	}
)

// Fill with you ideas below.
