// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberLogDao is internal type for wrapping internal DAO implements.
type internalPmsMemberLogDao = *internal.PmsMemberLogDao

// pmsMemberLogDao is the data access object for table hg_pms_member_log.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberLogDao struct {
	internalPmsMemberLogDao
}

var (
	// PmsMemberLog is globally public accessible object for table hg_pms_member_log operations.
	PmsMemberLog = pmsMemberLogDao{
		internal.NewPmsMemberLogDao(),
	}
)

// Fill with you ideas below.
