// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsPropertyRegionDao is internal type for wrapping internal DAO implements.
type internalPmsPropertyRegionDao = *internal.PmsPropertyRegionDao

// pmsPropertyRegionDao is the data access object for table hg_pms_property_region.
// You can define custom methods on it to extend its functionality as you wish.
type pmsPropertyRegionDao struct {
	internalPmsPropertyRegionDao
}

var (
	// PmsPropertyRegion is globally public accessible object for table hg_pms_property_region operations.
	PmsPropertyRegion = pmsPropertyRegionDao{
		internal.NewPmsPropertyRegionDao(),
	}
)

// Fill with you ideas below.
