// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAppconfigDao is internal type for wrapping internal DAO implements.
type internalPmsAppconfigDao = *internal.PmsAppconfigDao

// pmsAppconfigDao is the data access object for table hg_pms_appconfig.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAppconfigDao struct {
	internalPmsAppconfigDao
}

var (
	// PmsAppconfig is globally public accessible object for table hg_pms_appconfig operations.
	PmsAppconfig = pmsAppconfigDao{
		internal.NewPmsAppconfigDao(),
	}
)

// Fill with you ideas below.
