// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberIntentionDao is internal type for wrapping internal DAO implements.
type internalPmsMemberIntentionDao = *internal.PmsMemberIntentionDao

// pmsMemberIntentionDao is the data access object for table hg_pms_member_intention.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberIntentionDao struct {
	internalPmsMemberIntentionDao
}

var (
	// PmsMemberIntention is globally public accessible object for table hg_pms_member_intention operations.
	PmsMemberIntention = pmsMemberIntentionDao{
		internal.NewPmsMemberIntentionDao(),
	}
)

// Fill with you ideas below.
