// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsCouponTypeDao is internal type for wrapping internal DAO implements.
type internalPmsCouponTypeDao = *internal.PmsCouponTypeDao

// pmsCouponTypeDao is the data access object for table hg_pms_coupon_type.
// You can define custom methods on it to extend its functionality as you wish.
type pmsCouponTypeDao struct {
	internalPmsCouponTypeDao
}

var (
	// PmsCouponType is globally public accessible object for table hg_pms_coupon_type operations.
	PmsCouponType = pmsCouponTypeDao{
		internal.NewPmsCouponTypeDao(),
	}
)

// Fill with you ideas below.
