// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsLanguageDao is internal type for wrapping internal DAO implements.
type internalPmsLanguageDao = *internal.PmsLanguageDao

// pmsLanguageDao is the data access object for table hg_pms_language.
// You can define custom methods on it to extend its functionality as you wish.
type pmsLanguageDao struct {
	internalPmsLanguageDao
}

var (
	// PmsLanguage is globally public accessible object for table hg_pms_language operations.
	PmsLanguage = pmsLanguageDao{
		internal.NewPmsLanguageDao(),
	}
)

// Fill with you ideas below.
