// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsStaffDao is internal type for wrapping internal DAO implements.
type internalPmsStaffDao = *internal.PmsStaffDao

// pmsStaffDao is the data access object for table hg_pms_staff.
// You can define custom methods on it to extend its functionality as you wish.
type pmsStaffDao struct {
	internalPmsStaffDao
}

var (
	// PmsStaff is globally public accessible object for table hg_pms_staff operations.
	PmsStaff = pmsStaffDao{
		internal.NewPmsStaffDao(),
	}
)

// Fill with you ideas below.
