// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsRoomUnitDao is internal type for wrapping internal DAO implements.
type internalPmsRoomUnitDao = *internal.PmsRoomUnitDao

// pmsRoomUnitDao is the data access object for table hg_pms_room_unit.
// You can define custom methods on it to extend its functionality as you wish.
type pmsRoomUnitDao struct {
	internalPmsRoomUnitDao
}

var (
	// PmsRoomUnit is globally public accessible object for table hg_pms_room_unit operations.
	PmsRoomUnit = pmsRoomUnitDao{
		internal.NewPmsRoomUnitDao(),
	}
)

// Fill with you ideas below.
