// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsMemberCancelDao is internal type for wrapping internal DAO implements.
type internalPmsMemberCancelDao = *internal.PmsMemberCancelDao

// pmsMemberCancelDao is the data access object for table hg_pms_member_cancel.
// You can define custom methods on it to extend its functionality as you wish.
type pmsMemberCancelDao struct {
	internalPmsMemberCancelDao
}

var (
	// PmsMemberCancel is globally public accessible object for table hg_pms_member_cancel operations.
	PmsMemberCancel = pmsMemberCancelDao{
		internal.NewPmsMemberCancelDao(),
	}
)

// Fill with you ideas below.
