// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsTransactionRefundDao is internal type for wrapping internal DAO implements.
type internalPmsTransactionRefundDao = *internal.PmsTransactionRefundDao

// pmsTransactionRefundDao is the data access object for table hg_pms_transaction_refund.
// You can define custom methods on it to extend its functionality as you wish.
type pmsTransactionRefundDao struct {
	internalPmsTransactionRefundDao
}

var (
	// PmsTransactionRefund is globally public accessible object for table hg_pms_transaction_refund operations.
	PmsTransactionRefund = pmsTransactionRefundDao{
		internal.NewPmsTransactionRefundDao(),
	}
)

// Fill with you ideas below.
