// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsHelpcenterCategoryDao is internal type for wrapping internal DAO implements.
type internalPmsHelpcenterCategoryDao = *internal.PmsHelpcenterCategoryDao

// pmsHelpcenterCategoryDao is the data access object for table hg_pms_helpcenter_category.
// You can define custom methods on it to extend its functionality as you wish.
type pmsHelpcenterCategoryDao struct {
	internalPmsHelpcenterCategoryDao
}

var (
	// PmsHelpcenterCategory is globally public accessible object for table hg_pms_helpcenter_category operations.
	PmsHelpcenterCategory = pmsHelpcenterCategoryDao{
		internal.NewPmsHelpcenterCategoryDao(),
	}
)

// Fill with you ideas below.
