// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsRoomStatusDao is internal type for wrapping internal DAO implements.
type internalPmsRoomStatusDao = *internal.PmsRoomStatusDao

// pmsRoomStatusDao is the data access object for table hg_pms_room_status.
// You can define custom methods on it to extend its functionality as you wish.
type pmsRoomStatusDao struct {
	internalPmsRoomStatusDao
}

var (
	// PmsRoomStatus is globally public accessible object for table hg_pms_room_status operations.
	PmsRoomStatus = pmsRoomStatusDao{
		internal.NewPmsRoomStatusDao(),
	}
)

// Fill with you ideas below.
