// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsReferrerLogDao is internal type for wrapping internal DAO implements.
type internalPmsReferrerLogDao = *internal.PmsReferrerLogDao

// pmsReferrerLogDao is the data access object for table hg_pms_referrer_log.
// You can define custom methods on it to extend its functionality as you wish.
type pmsReferrerLogDao struct {
	internalPmsReferrerLogDao
}

var (
	// PmsReferrerLog is globally public accessible object for table hg_pms_referrer_log operations.
	PmsReferrerLog = pmsReferrerLogDao{
		internal.NewPmsReferrerLogDao(),
	}
)

// Fill with you ideas below.
