// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsAvailabilitiesDao is internal type for wrapping internal DAO implements.
type internalPmsAvailabilitiesDao = *internal.PmsAvailabilitiesDao

// pmsAvailabilitiesDao is the data access object for table hg_pms_availabilities.
// You can define custom methods on it to extend its functionality as you wish.
type pmsAvailabilitiesDao struct {
	internalPmsAvailabilitiesDao
}

var (
	// PmsAvailabilities is globally public accessible object for table hg_pms_availabilities operations.
	PmsAvailabilities = pmsAvailabilitiesDao{
		internal.NewPmsAvailabilitiesDao(),
	}
)

// Fill with you ideas below.
