// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsPropertyDao is internal type for wrapping internal DAO implements.
type internalPmsPropertyDao = *internal.PmsPropertyDao

// pmsPropertyDao is the data access object for table hg_pms_property.
// You can define custom methods on it to extend its functionality as you wish.
type pmsPropertyDao struct {
	internalPmsPropertyDao
}

var (
	// PmsProperty is globally public accessible object for table hg_pms_property operations.
	PmsProperty = pmsPropertyDao{
		internal.NewPmsPropertyDao(),
	}
)

// Fill with you ideas below.
