// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalPmsGuestProfileDao is internal type for wrapping internal DAO implements.
type internalPmsGuestProfileDao = *internal.PmsGuestProfileDao

// pmsGuestProfileDao is the data access object for table hg_pms_guest_profile.
// You can define custom methods on it to extend its functionality as you wish.
type pmsGuestProfileDao struct {
	internalPmsGuestProfileDao
}

var (
	// PmsGuestProfile is globally public accessible object for table hg_pms_guest_profile operations.
	PmsGuestProfile = pmsGuestProfileDao{
		internal.NewPmsGuestProfileDao(),
	}
)

// Fill with you ideas below.
