// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalProductOrderDao is internal type for wrapping internal DAO implements.
type internalProductOrderDao = *internal.ProductOrderDao

// productOrderDao is the data access object for table product_order.
// You can define custom methods on it to extend its functionality as you wish.
type productOrderDao struct {
	internalProductOrderDao
}

var (
	// ProductOrder is globally public accessible object for table product_order operations.
	ProductOrder = productOrderDao{
		internal.NewProductOrderDao(),
	}
)

// Fill with you ideas below.
