// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalQrcodeDao is internal type for wrapping internal DAO implements.
type internalQrcodeDao = *internal.QrcodeDao

// qrcodeDao is the data access object for table qrcode.
// You can define custom methods on it to extend its functionality as you wish.
type qrcodeDao struct {
	internalQrcodeDao
}

var (
	// Qrcode is globally public accessible object for table qrcode operations.
	Qrcode = qrcodeDao{
		internal.NewQrcodeDao(),
	}
)

// Fill with you ideas below.
