// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalRateDao is internal type for wrapping internal DAO implements.
type internalRateDao = *internal.RateDao

// rateDao is the data access object for table rate.
// You can define custom methods on it to extend its functionality as you wish.
type rateDao struct {
	internalRateDao
}

var (
	// Rate is globally public accessible object for table rate operations.
	Rate = rateDao{
		internal.NewRateDao(),
	}
)

// Fill with you ideas below.
