// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalReceiptDao is an internal type for wrapping the internal DAO implementation.
type internalReceiptDao = *internal.ReceiptDao

// receiptDao is the data access object for the table hg_receipt.
// You can define custom methods on it to extend its functionality as needed.
type receiptDao struct {
	internalReceiptDao
}

var (
	// Receipt is a globally accessible object for table hg_receipt operations.
	Receipt = receiptDao{
		internal.NewReceiptDao(),
	}
)

// Add your custom methods and functionality below.
