// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalReplyItemDao is internal type for wrapping internal DAO implements.
type internalReplyItemDao = *internal.ReplyItemDao

// replyItemDao is the data access object for table reply_item.
// You can define custom methods on it to extend its functionality as you wish.
type replyItemDao struct {
	internalReplyItemDao
}

var (
	// ReplyItem is globally public accessible object for table reply_item operations.
	ReplyItem = replyItemDao{
		internal.NewReplyItemDao(),
	}
)

// Fill with you ideas below.
