// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalReplyGroupDao is internal type for wrapping internal DAO implements.
type internalReplyGroupDao = *internal.ReplyGroupDao

// replyGroupDao is the data access object for table reply_group.
// You can define custom methods on it to extend its functionality as you wish.
type replyGroupDao struct {
	internalReplyGroupDao
}

var (
	// ReplyGroup is globally public accessible object for table reply_group operations.
	ReplyGroup = replyGroupDao{
		internal.NewReplyGroupDao(),
	}
)

// Fill with you ideas below.
