// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaBannerDao is internal type for wrapping internal DAO implements.
type internalSpaBannerDao = *internal.SpaBannerDao

// spaBannerDao is the data access object for table hg_spa_banner.
// You can define custom methods on it to extend its functionality as you wish.
type spaBannerDao struct {
	internalSpaBannerDao
}

var (
	// SpaBanner is globally public accessible object for table hg_spa_banner operations.
	SpaBanner = spaBannerDao{
		internal.NewSpaBannerDao(),
	}
)

// Fill with you ideas below.
