// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaIspDao is internal type for wrapping internal DAO implements.
type internalSpaIspDao = *internal.SpaIspDao

// spaIspDao is the data access object for table hg_spa_isp.
// You can define custom methods on it to extend its functionality as you wish.
type spaIspDao struct {
	internalSpaIspDao
}

var (
	// SpaIsp is globally public accessible object for table hg_spa_isp operations.
	SpaIsp = spaIspDao{
		internal.NewSpaIspDao(),
	}
)

// Fill with you ideas below.
