// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaOrderGoodsDao is internal type for wrapping internal DAO implements.
type internalSpaOrderGoodsDao = *internal.SpaOrderGoodsDao

// spaOrderGoodsDao is the data access object for table hg_spa_order_goods.
// You can define custom methods on it to extend its functionality as you wish.
type spaOrderGoodsDao struct {
	internalSpaOrderGoodsDao
}

var (
	// SpaOrderGoods is globally public accessible object for table hg_spa_order_goods operations.
	SpaOrderGoods = spaOrderGoodsDao{
		internal.NewSpaOrderGoodsDao(),
	}
)

// Fill with you ideas below.
