// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaTechnicianBalanceChangeDao is internal type for wrapping internal DAO implements.
type internalSpaTechnicianBalanceChangeDao = *internal.SpaTechnicianBalanceChangeDao

// spaTechnicianBalanceChangeDao is the data access object for table hg_spa_technician_balance_change.
// You can define custom methods on it to extend its functionality as you wish.
type spaTechnicianBalanceChangeDao struct {
	internalSpaTechnicianBalanceChangeDao
}

var (
	// SpaTechnicianBalanceChange is globally public accessible object for table hg_spa_technician_balance_change operations.
	SpaTechnicianBalanceChange = spaTechnicianBalanceChangeDao{
		internal.NewSpaTechnicianBalanceChangeDao(),
	}
)

// Fill with you ideas below.
