// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaSettlementOrderDao is internal type for wrapping internal DAO implements.
type internalSpaSettlementOrderDao = *internal.SpaSettlementOrderDao

// spaSettlementOrderDao is the data access object for table hg_spa_settlement_order.
// You can define custom methods on it to extend its functionality as you wish.
type spaSettlementOrderDao struct {
	internalSpaSettlementOrderDao
}

var (
	// SpaSettlementOrder is globally public accessible object for table hg_spa_settlement_order operations.
	SpaSettlementOrder = spaSettlementOrderDao{
		internal.NewSpaSettlementOrderDao(),
	}
)

// Fill with you ideas below.
