// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaOrderTechnicianDao is internal type for wrapping internal DAO implements.
type internalSpaOrderTechnicianDao = *internal.SpaOrderTechnicianDao

// spaOrderTechnicianDao is the data access object for table hg_spa_order_technician.
// You can define custom methods on it to extend its functionality as you wish.
type spaOrderTechnicianDao struct {
	internalSpaOrderTechnicianDao
}

var (
	// SpaOrderTechnician is globally public accessible object for table hg_spa_order_technician operations.
	SpaOrderTechnician = spaOrderTechnicianDao{
		internal.NewSpaOrderTechnicianDao(),
	}
)

// Fill with you ideas below.
