// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaServicePropertyDao is internal type for wrapping internal DAO implements.
type internalSpaServicePropertyDao = *internal.SpaServicePropertyDao

// spaServicePropertyDao is the data access object for table hg_spa_service_property.
// You can define custom methods on it to extend its functionality as you wish.
type spaServicePropertyDao struct {
	internalSpaServicePropertyDao
}

var (
	// SpaServiceProperty is globally public accessible object for table hg_spa_service_property operations.
	SpaServiceProperty = spaServicePropertyDao{
		internal.NewSpaServicePropertyDao(),
	}
)

// Fill with you ideas below.
