// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaLabelDao is internal type for wrapping internal DAO implements.
type internalSpaLabelDao = *internal.SpaLabelDao

// spaLabelDao is the data access object for table hg_spa_label.
// You can define custom methods on it to extend its functionality as you wish.
type spaLabelDao struct {
	internalSpaLabelDao
}

var (
	// SpaLabel is globally public accessible object for table hg_spa_label operations.
	SpaLabel = spaLabelDao{
		internal.NewSpaLabelDao(),
	}
)

// Fill with you ideas below.
