// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaServiceGoodsDao is internal type for wrapping internal DAO implements.
type internalSpaServiceGoodsDao = *internal.SpaServiceGoodsDao

// spaServiceGoodsDao is the data access object for table hg_spa_service_goods.
// You can define custom methods on it to extend its functionality as you wish.
type spaServiceGoodsDao struct {
	internalSpaServiceGoodsDao
}

var (
	// SpaServiceGoods is globally public accessible object for table hg_spa_service_goods operations.
	SpaServiceGoods = spaServiceGoodsDao{
		internal.NewSpaServiceGoodsDao(),
	}
)

// Fill with you ideas below.
