// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaSettlementDao is internal type for wrapping internal DAO implements.
type internalSpaSettlementDao = *internal.SpaSettlementDao

// spaSettlementDao is the data access object for table hg_spa_settlement.
// You can define custom methods on it to extend its functionality as you wish.
type spaSettlementDao struct {
	internalSpaSettlementDao
}

var (
	// SpaSettlement is globally public accessible object for table hg_spa_settlement operations.
	SpaSettlement = spaSettlementDao{
		internal.NewSpaSettlementDao(),
	}
)

// Fill with you ideas below.
