// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaCooperateTypeDao is internal type for wrapping internal DAO implements.
type internalSpaCooperateTypeDao = *internal.SpaCooperateTypeDao

// spaCooperateTypeDao is the data access object for table hg_spa_cooperate_type.
// You can define custom methods on it to extend its functionality as you wish.
type spaCooperateTypeDao struct {
	internalSpaCooperateTypeDao
}

var (
	// SpaCooperateType is globally public accessible object for table hg_spa_cooperate_type operations.
	SpaCooperateType = spaCooperateTypeDao{
		internal.NewSpaCooperateTypeDao(),
	}
)

// Fill with you ideas below.
