// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaStoreDao is internal type for wrapping internal DAO implements.
type internalSpaStoreDao = *internal.SpaStoreDao

// spaStoreDao is the data access object for table hg_spa_store.
// You can define custom methods on it to extend its functionality as you wish.
type spaStoreDao struct {
	internalSpaStoreDao
}

var (
	// SpaStore is globally public accessible object for table hg_spa_store operations.
	SpaStore = spaStoreDao{
		internal.NewSpaStoreDao(),
	}
)

// Fill with you ideas below.
