// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaTechnicianDao is internal type for wrapping internal DAO implements.
type internalSpaTechnicianDao = *internal.SpaTechnicianDao

// spaTechnicianDao is the data access object for table hg_spa_technician.
// You can define custom methods on it to extend its functionality as you wish.
type spaTechnicianDao struct {
	internalSpaTechnicianDao
}

var (
	// SpaTechnician is globally public accessible object for table hg_spa_technician operations.
	SpaTechnician = spaTechnicianDao{
		internal.NewSpaTechnicianDao(),
	}
)

// Fill with you ideas below.
