// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaServiceLabelDao is internal type for wrapping internal DAO implements.
type internalSpaServiceLabelDao = *internal.SpaServiceLabelDao

// spaServiceLabelDao is the data access object for table hg_spa_service_label.
// You can define custom methods on it to extend its functionality as you wish.
type spaServiceLabelDao struct {
	internalSpaServiceLabelDao
}

var (
	// SpaServiceLabel is globally public accessible object for table hg_spa_service_label operations.
	SpaServiceLabel = spaServiceLabelDao{
		internal.NewSpaServiceLabelDao(),
	}
)

// Fill with you ideas below.
