// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaOrderDao is internal type for wrapping internal DAO implements.
type internalSpaOrderDao = *internal.SpaOrderDao

// spaOrderDao is the data access object for table hg_spa_order.
// You can define custom methods on it to extend its functionality as you wish.
type spaOrderDao struct {
	internalSpaOrderDao
}

var (
	// SpaOrder is globally public accessible object for table hg_spa_order operations.
	SpaOrder = spaOrderDao{
		internal.NewSpaOrderDao(),
	}
)

// Fill with you ideas below.
