// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaOrderLogDao is internal type for wrapping internal DAO implements.
type internalSpaOrderLogDao = *internal.SpaOrderLogDao

// spaOrderLogDao is the data access object for table hg_spa_order_log.
// You can define custom methods on it to extend its functionality as you wish.
type spaOrderLogDao struct {
	internalSpaOrderLogDao
}

var (
	// SpaOrderLog is globally public accessible object for table hg_spa_order_log operations.
	SpaOrderLog = spaOrderLogDao{
		internal.NewSpaOrderLogDao(),
	}
)

// Fill with you ideas below.
