// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaServiceDao is internal type for wrapping internal DAO implements.
type internalSpaServiceDao = *internal.SpaServiceDao

// spaServiceDao is the data access object for table hg_spa_service.
// You can define custom methods on it to extend its functionality as you wish.
type spaServiceDao struct {
	internalSpaServiceDao
}

var (
	// SpaService is globally public accessible object for table hg_spa_service operations.
	SpaService = spaServiceDao{
		internal.NewSpaServiceDao(),
	}
)

// Fill with you ideas below.
