// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaMaintenanceDao is internal type for wrapping internal DAO implements.
type internalSpaMaintenanceDao = *internal.SpaMaintenanceDao

// spaMaintenanceDao is the data access object for table hg_spa_maintenance.
// You can define custom methods on it to extend its functionality as you wish.
type spaMaintenanceDao struct {
	internalSpaMaintenanceDao
}

var (
	// SpaMaintenance is globally public accessible object for table hg_spa_maintenance operations.
	SpaMaintenance = spaMaintenanceDao{
		internal.NewSpaMaintenanceDao(),
	}
)

// Fill with you ideas below.
