// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSpaIspBalanceChangeDao is internal type for wrapping internal DAO implements.
type internalSpaIspBalanceChangeDao = *internal.SpaIspBalanceChangeDao

// spaIspBalanceChangeDao is the data access object for table hg_spa_isp_balance_change.
// You can define custom methods on it to extend its functionality as you wish.
type spaIspBalanceChangeDao struct {
	internalSpaIspBalanceChangeDao
}

var (
	// SpaIspBalanceChange is globally public accessible object for table hg_spa_isp_balance_change operations.
	SpaIspBalanceChange = spaIspBalanceChangeDao{
		internal.NewSpaIspBalanceChangeDao(),
	}
)

// Fill with you ideas below.
