// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSysTerminalModelDao is internal type for wrapping internal DAO implements.
type internalSysTerminalModelDao = *internal.SysTerminalModelDao

// sysTerminalModelDao is the data access object for table hg_sys_terminal_model.
// You can define custom methods on it to extend its functionality as you wish.
type sysTerminalModelDao struct {
	internalSysTerminalModelDao
}

var (
	// SysTerminalModel is globally public accessible object for table hg_sys_terminal_model operations.
	SysTerminalModel = sysTerminalModelDao{
		internal.NewSysTerminalModelDao(),
	}
)

// Fill with you ideas below.
