// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSysSmsTemplateLogDao is internal type for wrapping internal DAO implements.
type internalSysSmsTemplateLogDao = *internal.SysSmsTemplateLogDao

// sysSmsTemplateLogDao is the data access object for table hg_sys_sms_template_log.
// You can define custom methods on it to extend its functionality as you wish.
type sysSmsTemplateLogDao struct {
	internalSysSmsTemplateLogDao
}

var (
	// SysSmsTemplateLog is globally public accessible object for table hg_sys_sms_template_log operations.
	SysSmsTemplateLog = sysSmsTemplateLogDao{
		internal.NewSysSmsTemplateLogDao(),
	}
)

// Fill with you ideas below.
