// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSysAttachmentKindDao is internal type for wrapping internal DAO implements.
type internalSysAttachmentKindDao = *internal.SysAttachmentKindDao

// sysAttachmentKindDao is the data access object for table hg_sys_attachment_kind.
// You can define custom methods on it to extend its functionality as you wish.
type sysAttachmentKindDao struct {
	internalSysAttachmentKindDao
}

var (
	// SysAttachmentKind is globally public accessible object for table hg_sys_attachment_kind operations.
	SysAttachmentKind = sysAttachmentKindDao{
		internal.NewSysAttachmentKindDao(),
	}
)

// Fill with you ideas below.
