// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSysTerminalDao is internal type for wrapping internal DAO implements.
type internalSysTerminalDao = *internal.SysTerminalDao

// sysTerminalDao is the data access object for table hg_sys_terminal.
// You can define custom methods on it to extend its functionality as you wish.
type sysTerminalDao struct {
	internalSysTerminalDao
}

var (
	// SysTerminal is globally public accessible object for table hg_sys_terminal operations.
	SysTerminal = sysTerminalDao{
		internal.NewSysTerminalDao(),
	}
)

// Fill with you ideas below.
