// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSysPrinterDao is internal type for wrapping internal DAO implements.
type internalSysPrinterDao = *internal.SysPrinterDao

// sysPrinterDao is the data access object for table hg_sys_printer.
// You can define custom methods on it to extend its functionality as you wish.
type sysPrinterDao struct {
	internalSysPrinterDao
}

var (
	// SysPrinter is globally public accessible object for table hg_sys_printer operations.
	SysPrinter = sysPrinterDao{
		internal.NewSysPrinterDao(),
	}
)

// Fill with you ideas below.
