// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSysSmsTemplateDao is internal type for wrapping internal DAO implements.
type internalSysSmsTemplateDao = *internal.SysSmsTemplateDao

// sysSmsTemplateDao is the data access object for table hg_sys_sms_template.
// You can define custom methods on it to extend its functionality as you wish.
type sysSmsTemplateDao struct {
	internalSysSmsTemplateDao
}

var (
	// SysSmsTemplate is globally public accessible object for table hg_sys_sms_template operations.
	SysSmsTemplate = sysSmsTemplateDao{
		internal.NewSysSmsTemplateDao(),
	}
)

// Fill with you ideas below.
