// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSysTerminalVerifyDao is internal type for wrapping internal DAO implements.
type internalSysTerminalVerifyDao = *internal.SysTerminalVerifyDao

// sysTerminalVerifyDao is the data access object for table hg_sys_terminal_verify.
// You can define custom methods on it to extend its functionality as you wish.
type sysTerminalVerifyDao struct {
	internalSysTerminalVerifyDao
}

var (
	// SysTerminalVerify is globally public accessible object for table hg_sys_terminal_verify operations.
	SysTerminalVerify = sysTerminalVerifyDao{
		internal.NewSysTerminalVerifyDao(),
	}
)

// Fill with you ideas below.
