// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSystemMessageReadDao is internal type for wrapping internal DAO implements.
type internalSystemMessageReadDao = *internal.SystemMessageReadDao

// systemMessageReadDao is the data access object for table hg_system_message_read.
// You can define custom methods on it to extend its functionality as you wish.
type systemMessageReadDao struct {
	internalSystemMessageReadDao
}

var (
	// SystemMessageRead is globally public accessible object for table hg_system_message_read operations.
	SystemMessageRead = systemMessageReadDao{
		internal.NewSystemMessageReadDao(),
	}
)

// Fill with you ideas below.
