// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalSystemMessageDao is internal type for wrapping internal DAO implements.
type internalSystemMessageDao = *internal.SystemMessageDao

// systemMessageDao is the data access object for table hg_system_message.
// You can define custom methods on it to extend its functionality as you wish.
type systemMessageDao struct {
	internalSystemMessageDao
}

var (
	// SystemMessage is globally public accessible object for table hg_system_message operations.
	SystemMessage = systemMessageDao{
		internal.NewSystemMessageDao(),
	}
)

// Fill with you ideas below.
