// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThCouponMchDao is internal type for wrapping internal DAO implements.
type internalThCouponMchDao = *internal.ThCouponMchDao

// thCouponMchDao is the data access object for table hg_th_coupon_mch.
// You can define custom methods on it to extend its functionality as you wish.
type thCouponMchDao struct {
	internalThCouponMchDao
}

var (
	// ThCouponMch is globally public accessible object for table hg_th_coupon_mch operations.
	ThCouponMch = thCouponMchDao{
		internal.NewThCouponMchDao(),
	}
)

// Fill with you ideas below.
