// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThCouponDao is internal type for wrapping internal DAO implements.
type internalThCouponDao = *internal.ThCouponDao

// thCouponDao is the data access object for table hg_th_coupon.
// You can define custom methods on it to extend its functionality as you wish.
type thCouponDao struct {
	internalThCouponDao
}

var (
	// ThCoupon is globally public accessible object for table hg_th_coupon operations.
	ThCoupon = thCouponDao{
		internal.NewThCouponDao(),
	}
)

// Fill with you ideas below.
