// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThCouponCategoryDao is internal type for wrapping internal DAO implements.
type internalThCouponCategoryDao = *internal.ThCouponCategoryDao

// thCouponCategoryDao is the data access object for table hg_th_coupon_category.
// You can define custom methods on it to extend its functionality as you wish.
type thCouponCategoryDao struct {
	internalThCouponCategoryDao
}

var (
	// ThCouponCategory is globally public accessible object for table hg_th_coupon_category operations.
	ThCouponCategory = thCouponCategoryDao{
		internal.NewThCouponCategoryDao(),
	}
)

// Fill with you ideas below.
