// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThMemberCouponDao is internal type for wrapping internal DAO implements.
type internalThMemberCouponDao = *internal.ThMemberCouponDao

// thMemberCouponDao is the data access object for table hg_th_member_coupon.
// You can define custom methods on it to extend its functionality as you wish.
type thMemberCouponDao struct {
	internalThMemberCouponDao
}

var (
	// ThMemberCoupon is globally public accessible object for table hg_th_member_coupon operations.
	ThMemberCoupon = thMemberCouponDao{
		internal.NewThMemberCouponDao(),
	}
)

// Fill with you ideas below.
