// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThMchCategoryDao is internal type for wrapping internal DAO implements.
type internalThMchCategoryDao = *internal.ThMchCategoryDao

// thMchCategoryDao is the data access object for table hg_th_mch_category.
// You can define custom methods on it to extend its functionality as you wish.
type thMchCategoryDao struct {
	internalThMchCategoryDao
}

var (
	// ThMchCategory is globally public accessible object for table hg_th_mch_category operations.
	ThMchCategory = thMchCategoryDao{
		internal.NewThMchCategoryDao(),
	}
)

// Fill with you ideas below.
