// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThMchStoreDao is internal type for wrapping internal DAO implements.
type internalThMchStoreDao = *internal.ThMchStoreDao

// thMchStoreDao is the data access object for table hg_th_mch_store.
// You can define custom methods on it to extend its functionality as you wish.
type thMchStoreDao struct {
	internalThMchStoreDao
}

var (
	// ThMchStore is globally public accessible object for table hg_th_mch_store operations.
	ThMchStore = thMchStoreDao{
		internal.NewThMchStoreDao(),
	}
)

// Fill with you ideas below.
