// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThMchDao is internal type for wrapping internal DAO implements.
type internalThMchDao = *internal.ThMchDao

// thMchDao is the data access object for table hg_th_mch.
// You can define custom methods on it to extend its functionality as you wish.
type thMchDao struct {
	internalThMchDao
}

var (
	// ThMch is globally public accessible object for table hg_th_mch operations.
	ThMch = thMchDao{
		internal.NewThMchDao(),
	}
)

// Fill with you ideas below.
