// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalThStoreTerminalDao is internal type for wrapping internal DAO implements.
type internalThStoreTerminalDao = *internal.ThStoreTerminalDao

// thStoreTerminalDao is the data access object for table hg_th_store_terminal.
// You can define custom methods on it to extend its functionality as you wish.
type thStoreTerminalDao struct {
	internalThStoreTerminalDao
}

var (
	// ThStoreTerminal is globally public accessible object for table hg_th_store_terminal operations.
	ThStoreTerminal = thStoreTerminalDao{
		internal.NewThStoreTerminalDao(),
	}
)

// Fill with you ideas below.
