// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalToretaNotificationFailedLogDao is internal type for wrapping internal DAO implements.
type internalToretaNotificationFailedLogDao = *internal.ToretaNotificationFailedLogDao

// toretaNotificationFailedLogDao is the data access object for table hg_toreta_notification_failed_log.
// You can define custom methods on it to extend its functionality as you wish.
type toretaNotificationFailedLogDao struct {
	internalToretaNotificationFailedLogDao
}

var (
	// ToretaNotificationFailedLog is globally public accessible object for table hg_toreta_notification_failed_log operations.
	ToretaNotificationFailedLog = toretaNotificationFailedLogDao{
		internal.NewToretaNotificationFailedLogDao(),
	}
)

// Fill with you ideas below.
