// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalTravelVerifyRecordDao is internal type for wrapping internal DAO implements.
type internalTravelVerifyRecordDao = *internal.TravelVerifyRecordDao

// travelVerifyRecordDao is the data access object for table hg_travel_verify_record.
// You can define custom methods on it to extend its functionality as you wish.
type travelVerifyRecordDao struct {
	internalTravelVerifyRecordDao
}

var (
	// TravelVerifyRecord is globally public accessible object for table hg_travel_verify_record operations.
	TravelVerifyRecord = travelVerifyRecordDao{
		internal.NewTravelVerifyRecordDao(),
	}
)

// Fill with you ideas below.
