// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalTravelVerifyStaffDao is internal type for wrapping internal DAO implements.
type internalTravelVerifyStaffDao = *internal.TravelVerifyStaffDao

// travelVerifyStaffDao is the data access object for table hg_travel_verify_staff.
// You can define custom methods on it to extend its functionality as you wish.
type travelVerifyStaffDao struct {
	internalTravelVerifyStaffDao
}

var (
	// TravelVerifyStaff is globally public accessible object for table hg_travel_verify_staff operations.
	TravelVerifyStaff = travelVerifyStaffDao{
		internal.NewTravelVerifyStaffDao(),
	}
)

// Fill with you ideas below.
