// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalTravelOrderLogDao is internal type for wrapping internal DAO implements.
type internalTravelOrderLogDao = *internal.TravelOrderLogDao

// travelOrderLogDao is the data access object for table hg_travel_order_log.
// You can define custom methods on it to extend its functionality as you wish.
type travelOrderLogDao struct {
	internalTravelOrderLogDao
}

var (
	// TravelOrderLog is globally public accessible object for table hg_travel_order_log operations.
	TravelOrderLog = travelOrderLogDao{
		internal.NewTravelOrderLogDao(),
	}
)

// Fill with you ideas below.
