// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalTravelVerifyStaffScopeDao is internal type for wrapping internal DAO implements.
type internalTravelVerifyStaffScopeDao = *internal.TravelVerifyStaffScopeDao

// travelVerifyStaffScopeDao is the data access object for table hg_travel_verify_staff_scope.
// You can define custom methods on it to extend its functionality as you wish.
type travelVerifyStaffScopeDao struct {
	internalTravelVerifyStaffScopeDao
}

var (
	// TravelVerifyStaffScope is globally public accessible object for table hg_travel_verify_staff_scope operations.
	TravelVerifyStaffScope = travelVerifyStaffScopeDao{
		internal.NewTravelVerifyStaffScopeDao(),
	}
)

// Fill with you ideas below.
