// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalTravelProductSkuDao is internal type for wrapping internal DAO implements.
type internalTravelProductSkuDao = *internal.TravelProductSkuDao

// travelProductSkuDao is the data access object for table hg_travel_product_sku.
// You can define custom methods on it to extend its functionality as you wish.
type travelProductSkuDao struct {
	internalTravelProductSkuDao
}

var (
	// TravelProductSku is globally public accessible object for table hg_travel_product_sku operations.
	TravelProductSku = travelProductSkuDao{
		internal.NewTravelProductSkuDao(),
	}
)

// Fill with you ideas below.
