// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalTravelProductDao is internal type for wrapping internal DAO implements.
type internalTravelProductDao = *internal.TravelProductDao

// travelProductDao is the data access object for table hg_travel_product.
// You can define custom methods on it to extend its functionality as you wish.
type travelProductDao struct {
	internalTravelProductDao
}

var (
	// TravelProduct is globally public accessible object for table hg_travel_product operations.
	TravelProduct = travelProductDao{
		internal.NewTravelProductDao(),
	}
)

// Fill with you ideas below.
