// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalTravelOrderDao is internal type for wrapping internal DAO implements.
type internalTravelOrderDao = *internal.TravelOrderDao

// travelOrderDao is the data access object for table hg_travel_order.
// You can define custom methods on it to extend its functionality as you wish.
type travelOrderDao struct {
	internalTravelOrderDao
}

var (
	// TravelOrder is globally public accessible object for table hg_travel_order operations.
	TravelOrder = travelOrderDao{
		internal.NewTravelOrderDao(),
	}
)

// Fill with you ideas below.
