// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalUpDownLineDao is internal type for wrapping internal DAO implements.
type internalUpDownLineDao = *internal.UpDownLineDao

// upDownLineDao is the data access object for table up_down_line.
// You can define custom methods on it to extend its functionality as you wish.
type upDownLineDao struct {
	internalUpDownLineDao
}

var (
	// UpDownLine is globally public accessible object for table up_down_line operations.
	UpDownLine = upDownLineDao{
		internal.NewUpDownLineDao(),
	}
)

// Fill with you ideas below.
