// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalUserAttrDao is internal type for wrapping internal DAO implements.
type internalUserAttrDao = *internal.UserAttrDao

// userAttrDao is the data access object for table user_attr.
// You can define custom methods on it to extend its functionality as you wish.
type userAttrDao struct {
	internalUserAttrDao
}

var (
	// UserAttr is globally public accessible object for table user_attr operations.
	UserAttr = userAttrDao{
		internal.NewUserAttrDao(),
	}
)

// Fill with you ideas below.
