// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalUserClientDao is internal type for wrapping internal DAO implements.
type internalUserClientDao = *internal.UserClientDao

// userClientDao is the data access object for table user_client.
// You can define custom methods on it to extend its functionality as you wish.
type userClientDao struct {
	internalUserClientDao
}

var (
	// UserClient is globally public accessible object for table user_client operations.
	UserClient = userClientDao{
		internal.NewUserClientDao(),
	}
)

// Fill with you ideas below.
