// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalUserOrderDao is internal type for wrapping internal DAO implements.
type internalUserOrderDao = *internal.UserOrderDao

// userOrderDao is the data access object for table user_order.
// You can define custom methods on it to extend its functionality as you wish.
type userOrderDao struct {
	internalUserOrderDao
}

var (
	// UserOrder is globally public accessible object for table user_order operations.
	UserOrder = userOrderDao{
		internal.NewUserOrderDao(),
	}
)

// Fill with you ideas below.
