// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalUserDouyinDao is internal type for wrapping internal DAO implements.
type internalUserDouyinDao = *internal.UserDouyinDao

// userDouyinDao is the data access object for table user_douyin.
// You can define custom methods on it to extend its functionality as you wish.
type userDouyinDao struct {
	internalUserDouyinDao
}

var (
	// UserDouyin is globally public accessible object for table user_douyin operations.
	UserDouyin = userDouyinDao{
		internal.NewUserDouyinDao(),
	}
)

// Fill with you ideas below.
