// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalVirtualProductDao is internal type for wrapping internal DAO implements.
type internalVirtualProductDao = *internal.VirtualProductDao

// virtualProductDao is the data access object for table virtual_product.
// You can define custom methods on it to extend its functionality as you wish.
type virtualProductDao struct {
	internalVirtualProductDao
}

var (
	// VirtualProduct is globally public accessible object for table virtual_product operations.
	VirtualProduct = virtualProductDao{
		internal.NewVirtualProductDao(),
	}
)

// Fill with you ideas below.
