// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalVisitorAttrDao is internal type for wrapping internal DAO implements.
type internalVisitorAttrDao = *internal.VisitorAttrDao

// visitorAttrDao is the data access object for table visitor_attr.
// You can define custom methods on it to extend its functionality as you wish.
type visitorAttrDao struct {
	internalVisitorAttrDao
}

var (
	// VisitorAttr is globally public accessible object for table visitor_attr operations.
	VisitorAttr = visitorAttrDao{
		internal.NewVisitorAttrDao(),
	}
)

// Fill with you ideas below.
