// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalVisitorBlackDao is internal type for wrapping internal DAO implements.
type internalVisitorBlackDao = *internal.VisitorBlackDao

// visitorBlackDao is the data access object for table visitor_black.
// You can define custom methods on it to extend its functionality as you wish.
type visitorBlackDao struct {
	internalVisitorBlackDao
}

var (
	// VisitorBlack is globally public accessible object for table visitor_black operations.
	VisitorBlack = visitorBlackDao{
		internal.NewVisitorBlackDao(),
	}
)

// Fill with you ideas below.
