// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalVisitorExtDao is internal type for wrapping internal DAO implements.
type internalVisitorExtDao = *internal.VisitorExtDao

// visitorExtDao is the data access object for table visitor_ext.
// You can define custom methods on it to extend its functionality as you wish.
type visitorExtDao struct {
	internalVisitorExtDao
}

var (
	// VisitorExt is globally public accessible object for table visitor_ext operations.
	VisitorExt = visitorExtDao{
		internal.NewVisitorExtDao(),
	}
)

// Fill with you ideas below.
