// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalVisitorTagDao is internal type for wrapping internal DAO implements.
type internalVisitorTagDao = *internal.VisitorTagDao

// visitorTagDao is the data access object for table visitor_tag.
// You can define custom methods on it to extend its functionality as you wish.
type visitorTagDao struct {
	internalVisitorTagDao
}

var (
	// VisitorTag is globally public accessible object for table visitor_tag operations.
	VisitorTag = visitorTagDao{
		internal.NewVisitorTagDao(),
	}
)

// Fill with you ideas below.
