// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalWechatLoginDao is internal type for wrapping internal DAO implements.
type internalWechatLoginDao = *internal.WechatLoginDao

// wechatLoginDao is the data access object for table wechat_login.
// You can define custom methods on it to extend its functionality as you wish.
type wechatLoginDao struct {
	internalWechatLoginDao
}

var (
	// WechatLogin is globally public accessible object for table wechat_login operations.
	WechatLogin = wechatLoginDao{
		internal.NewWechatLoginDao(),
	}
)

// Fill with you ideas below.
