// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalWelcomeDao is internal type for wrapping internal DAO implements.
type internalWelcomeDao = *internal.WelcomeDao

// welcomeDao is the data access object for table welcome.
// You can define custom methods on it to extend its functionality as you wish.
type welcomeDao struct {
	internalWelcomeDao
}

var (
	// Welcome is globally public accessible object for table welcome operations.
	Welcome = welcomeDao{
		internal.NewWelcomeDao(),
	}
)

// Fill with you ideas below.
