// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"APT/internal/dao/internal"
)

// internalWeworkSyncMsgDao is internal type for wrapping internal DAO implements.
type internalWeworkSyncMsgDao = *internal.WeworkSyncMsgDao

// weworkSyncMsgDao is the data access object for table wework_sync_msg.
// You can define custom methods on it to extend its functionality as you wish.
type weworkSyncMsgDao struct {
	internalWeworkSyncMsgDao
}

var (
	// WeworkSyncMsg is globally public accessible object for table wework_sync_msg operations.
	WeworkSyncMsg = weworkSyncMsgDao{
		internal.NewWeworkSyncMsgDao(),
	}
)

// Fill with you ideas below.
