// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package inner

import (
	"APT/api/inner/system_message"
	"APT/internal/library/systemMessage"
	"context"
	"fmt"

	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/frame/g"
)

type ControllerSystemMessage struct{}


// GetSystemMessageList 获取系统消息列表
func (c *ControllerSystemMessage) GetSystemMessageList(ctx context.Context, req *system_message.GetSystemMessageListReq) (res *system_message.GetSystemMessageListRes, err error) {
	// 调用systemMessage库获取消息列表
	messages, total, err := systemMessage.GetMessagesByMember(ctx, req.MemberId, req.Page, req.PageSize)
	if err != nil {
		return nil, gerror.Wrap(err, "获取消息列表失败")
	}

	// 转换结果
	list := make([]system_message.SystemMessageItem, 0, len(messages))
	for _, msg := range messages {
		item := system_message.SystemMessageItem{
			Id:                msg.Id,
			Scene:             msg.Scene,
			Type:              msg.Type,
			Image:             msg.Image,
			AppLink:           msg.AppLink,
			WxLink:            msg.WxLink,
			MobilePushSuccess: &msg.MobilePushSuccess,
			MobileSmsSuccess:  &msg.MobileSmsSuccess,
			CreatedAt:         msg.CreatedAt.String(),
		}

		// 处理多语言标题和内容
		if msg.Title != nil {
			if titleStr := msg.Title.Get(req.Language).String(); titleStr != "" {
				item.Title = titleStr
			} else {
				item.Title = msg.Title.Get("zh").String() // 默认中文
			}
		}

		if msg.Content != nil {
			if contentStr := msg.Content.Get(req.Language).String(); contentStr != "" {
				item.Content = contentStr
			} else {
				item.Content = msg.Content.Get("zh").String() // 默认中文
			}
		}

		// 处理URL参数
		if msg.UrlParam != nil {
			item.UrlParam = msg.UrlParam.String()
		}

		list = append(list, item)
	}

	// 获取未读消息数量
	unreadCount, err := systemMessage.GetUnreadCount(ctx, req.MemberId)
	if err != nil {
		g.Log().Warning(ctx, "查询未读消息数量失败", "error", err)
		unreadCount = 0
	}

	res = &system_message.GetSystemMessageListRes{
		List:        list,
		Total:       total,
		Page:        req.Page,
		PageSize:    req.PageSize,
		UnreadCount: unreadCount,
	}

	return res, nil
}

// MarkMessageRead 标记消息已读
func (c *ControllerSystemMessage) MarkMessageRead(ctx context.Context, req *system_message.MarkMessageReadReq) (res *system_message.MarkMessageReadRes, err error) {
	res = &system_message.MarkMessageReadRes{
		Errors: make([]string, 0),
	}

	for _, messageId := range req.MessageIds {
		err := systemMessage.MarkMessageAsRead(ctx, messageId, req.MemberId)
		if err != nil {
			res.FailCount++
			res.Errors = append(res.Errors, fmt.Sprintf("消息%d标记已读失败: %s", messageId, err.Error()))
		} else {
			res.SuccessCount++
		}
	}

	return res, nil
}

// GetUnreadCount 获取未读消息数量
func (c *ControllerSystemMessage) GetUnreadCount(ctx context.Context, req *system_message.GetUnreadCountReq) (res *system_message.GetUnreadCountRes, err error) {
	unreadCount, err := systemMessage.GetUnreadCount(ctx, req.MemberId)
	if err != nil {
		return nil, gerror.Wrap(err, "查询未读消息数量失败")
	}

	res = &system_message.GetUnreadCountRes{
		UnreadCount: unreadCount,
	}

	return res, nil
}
