// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package inner

import (
	"APT/api/inner"
)

type ControllerOrder struct{}

func NewOrder() inner.IInnerOrder {
	return &ControllerOrder{}
}

func NewSystemMessage() inner.IInnerSystem_message {
	return &ControllerSystemMessage{}
}
